//./jshttp(1).js
{
"spider":"./top98_1.jar",
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"豆瓣","name":"豆瓣2🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"海外看资源网","name":"🌟海外看haiwaikan","type":0,"api":"https://haiwaikan.com/api.php/provide/vod/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"量子资源網","name":"🌟量子资源lz","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"categories":["国产剧","国产动漫","泰国剧","台湾剧","香港剧","欧美剧","韩国剧","日本剧","动漫","体育","剧情片","动作片","爱情片","喜剧片"]},
{"key":"淘片资源网","name":"🌟淘片资源tp","type":0,"api":"https://taopianapi.com/home/cjapi/as/mc/vod/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"非凡资源网","name":"🌟非凡资源ff","type":0,"api":"http://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"68资源网","name":"🌟68资源68","type":0,"api":"https://caiji.68zyapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"優質资源网","name":"🌟優質资源1080","type":0,"api":"https://api.1080zyku.com/inc/api.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"飛速资源网","name":"🌟飛速资源fe","type":0,"api":"https://www.feisuzyapi.com/api.php/provide/vod/from/fsm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快车资源網","name":"🌟快车资源kc","type":1,"api":"https://caiji.kczyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快播资源網","name":"🌟快播资源kb","type":1,"api":"http://www.kuaibozy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"樱花资源網","name":"🌟樱花资源yh","type":1,"api":"https://m3u8.apiyhzy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"卧龙资源網","name":"🌟卧龙资源wolong","type":1,"api":"https://collect.wolongzyw.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"新浪资源","name":"🌟新浪资源xl","type":0,"api":"https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"起飞影院網","name":"🌎起飞影院💬","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"鱼乐资源網","name":"🌕鱼乐资源le","type":1,"api":"https://api.ylzy1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"U酷资源網","name":"🌕U酷资源uk","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鷹资源网","name":"🌕金鷹资源jyz","type":0,"api":"https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"红牛资源","name":"🌕红牛资源hn","type":0,"api":"https://www.hongniuzy2.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"百度资源网","name":"🌕百度资源db","type":0,"api":"https://api.apibdzy.com/api.php/provide/vod/from/dbm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"FOX资源","name":"😰FOX资源fox","type":1,"api":"https://api.foxzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"光速资源","name":"😰光速资源gs","type":0,"api":"https://api.guangsuapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"速影","name":"😰速影動漫wj","type":1,"api":"https://速影128.xyz/inc/apijson.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"闪电资源","name":"😰闪电资源sd","type":1,"api":"http://sdzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"酷点资源网","name":"😰酷点资源网kd","type":0,"api":" https://kudian10.com/api.php/provide/vod/from/kdm3u8/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"无尽资源网","name":"😰无尽资源wj","type":0,"api":"https://api.wujinapi.me/api.php/provide/vod/from/wjm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"drpy_js_360影视","name":"官源🏛360","type":3,"api":"./lib/drpy2.min.js","ext":"./js/360影视.js"},
{"key":"drpy_js_奇珍异兽","name":"官源🏛爱奇艺🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽.js","url":"https://jx.zhanlangbu.com/?url="},
{"key":"drpy_js_优酷","name":"官源🏛优酷🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/优酷.js","url":"https://jx.zhanlangbu.com/?url="},
{"key":"drpy_js_腾云驾雾","name":"官源🏛腾讯🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/腾云驾雾.js"},
{"key":"drpy_js_百忙无果","name":"官源🏛芒果🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/百忙无果.js","url":"http://xn--wnup5g.xn--z7x900a.love:63/Art1/analysis.php?v="},
{"key":"drpy_js_菜狗","name":"官源🏛搜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗.js"},

{"key":"粤爱看","name":"🇭🇰粤爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/粤爱看.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源(1).txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules": [ 
{"host":"*", "rule":["douyinvod.com", "/video/tos/cn/"]}, 
{"host":"*", "rule":["default.365yg.com", "/video/tos/cn/"]}, 
{"host":"*","rule":["ysting.ysxs8.vip","m4a"]},
{"host":"*", "rule":["/m3u8.php?path=", ".m3u8"]}, 
{"host":"*", "rule":["/API.php?time=", "key=", "path=", ".m3u8"]}, 
{"host":"*", "rule":["oss-cn-m3u8", "myqcloud.com.zh188.net", "?url=", ".m3u8"]}, 
{"host":"*", "rule":["iesdouyin.com/aweme", "video_id="]},
{"host":"*", "rule":["douyin.com/aweme", "video_id="]},
{"host":"*", "rule":["huoshan.com", "/item/video/"]}, 
{"host":"*", "rule":["http((?!http).){12,}?\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)\\?.*"]}, 
{"host":"*", "rule":["http((?!http).){12,}\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)"]},
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".m3u8"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mp4"]}, 
{"host":"*", "rule":["aliyundrive.net", "response-content-disposition=", ".mkv"]}, 
{"host":"www.007ts.me", "rule":["hls.pchj.net", ".m3u8"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time="]},
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},
{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},
{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}
],
"parses":[
{"name":"聚合1","type":3,"url":"Demo"},
{"name":"聚合0","type":3,"url":"Web"},
{"name":"貓爪愛奇藝優酷🏆","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"不用芒果🏆","type":1,"url":"http://xn--wnup5g.xn--z7x900a.love:63/Art1/analysis.php?v=","ext":{"flag":["qq","腾讯","企鹅","IQiYi","qiyi","爱奇艺","奇艺","youku","YouKu","优酷","sohu","SoHu","搜狐","letv","LeShi","乐视","imgo","mgtv","MangGuo","芒果","SLYS4k","BYGA","luanzi","AliS","dxzy","bilibili","QEYSS","xigua","西瓜视频","腾讯视频","奇艺视频","优酷视频","芒果视频","乐视视频"]}},
{"name":"5号线芒1","type":0,"url":"https://jx.bozrc.com:4433/player/?url="},
{"name":"2号芒2優2","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url="},
{"name":"看看芒3","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"1号线","type":0,"url":"https://jx.777jiexi.com/player/?url="},
{"name":"3号线芒2","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"4号线芒3","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"1080","type":0,"url":"https://vip.zykbf.com/?url="},
{"name":"樱花","type":0,"url":"https://jx.yhzybf.com/player/jx.php?url="},
{"name":"大地","type":0,"url":"https://play.dadiapi.com/watch?url="},
{"name":"188","type":0,"url":"https://jiexi.xxzy.org/?url="},
{"name":"森林","type":0,"url":"https://sljxsl.com/?url="},
{"name":"新浪","type":0,"url":"https://www.xinlangjiexi.com/m3u8/?url="},
{"name":"523","type":0,"url":"https://api.523zyw.me/?url="},
{"name":"草莓","type":0,"url":"https://jiexi.caomeiapi.com/?url="},
{"name":"非凡","type":0,"url":"https://ffzyplayer.com/?url="},
{"name":"速播","type":0,"url":"https://subojiexi.com/play/?url="},
{"name":"ikun","type":0,"url":"https://www.ikdmjx.com/?url="},
{"name":"M3U8TV","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"江南","type":0,"url":"http://player.yjiexi.com/player?url="},
{"name":"68zy","type":0,"url":"https://jiexi.68zy.vip/m3u8/?url="},
{"name":"萌果","type":0,"url":"https://jx.sujx.top/jiexi.php/?url="},
{"name":"酷点","type":0,"url":"https://jx.kujiexi.net/m3u8.php?url="},
{"name":"无尽","type":0,"url":"https://jx.xhswglobal.com/dplayer/?url="},
{"name":"飞速","type":0,"url":"https://www.feisuplayer.com/m3u8/?url="},
{"name":"闪电","type":0,"url":"https://www.shankubf.com/m3u8/?url="},
{"name":"光速","type":0,"url":"https://www.guangsujx.com/m3u8/?url="},
{"name":"鱼乐","type":0,"url":"https://jx.ylbfq.com/dplayer/?url="},
{"name":"卧龙","type":0,"url":"https://jx.wolongzywcdn.com:65/m3u8.php?url="},
{"name":"量子","type":0,"url":"https://lziplayer.com/?url="},
{"name":"fox","type":0,"url":"https://www.foxbfq.com/dplayer/?url="},
{"name":"16号线QQ3","type":0,"url":"https://jx.jsonplayer.com/player/?url="},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url="}
],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg",
    "ads": [
        "vip.ffzyad.com",
        "iqiyi.hbuioo.com",
        "https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd",
        "mimg.0c1q0l.cn",
        "www.googletagmanager.com",
        "www.google-analytics.com",
        "mc.usihnbcq.cn",
        "mg.g1mm3d.cn",
        "mscs.svaeuzh.cn",
        "cnzz.hhttm.top",
        "tp.vinuxhome.com",
        "cnzz.mmstat.com",
        "www.baihuillq.com",
        "s23.cnzz.com",
        "z3.cnzz.com",
        "c.cnzz.com",
        "stj.v1vo.top",
        "z12.cnzz.com",
        "img.mosflower.cn",
        "tips.gamevvip.com",
        "ehwe.yhdtns.com",
        "xdn.cqqc3.com",
        "www.jixunkyy.cn",
        "sp.chemacid.cn",
        "hm.baidu.com",
        "s9.cnzz.com",
        "z6.cnzz.com",
        "um.cavuc.com",
        "mav.mavuz.com",
        "wofwk.aoidf3.com",
        "z5.cnzz.com",
        "xc.hubeijieshikj.cn",
        "tj.tianwenhu.com",
        "xg.gars57.cn",
        "k.jinxiuzhilv.com",
        "cdn.bootcss.com",
        "ppl.xunzhuo123.com",
        "xomk.jiangjunmh.top",
        "img.xunzhuo123.com",
        "z1.cnzz.com",
        "s13.cnzz.com",
        "xg.huataisangao.cn",
        "z7.cnzz.com",
        "xg.huataisangao.cn",
        "z2.cnzz.com",
        "s96.cnzz.com",
        "q11.cnzz.com",
        "thy.dacedsfa.cn",
        "xg.whsbpw.cn",
        "s19.cnzz.com",
        "z8.cnzz.com",
        "s4.cnzz.com",
        "f5w.as12df.top",
        "ae01.alicdn.com",
        "www.92424.cn",
        "k.wudejia.com",
        "vivovip.mmszxc.top",
        "qiu.xixiqiu.com",
        "cdnjs.hnfenxun.com",
        "cms.qdwght.com"
    ]
}