//./jshttp(1).js
{
//"spider" : "./FongMi_custom_spider.jar",
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"豆瓣","name":"豆瓣2🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"7喜影院","name":"👉🏆7喜影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/7喜影院(1).js"},
{"key":"AB影院[飞]","name":"🛩🈵AB影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AB影院[飞].js"},
{"key":"gaze","name":"💬gaze🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/gaze.js"},
{"key":"欧乐影院[飞]","name":"🛩歐樂影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/欧乐影院[飞](1).js"},
{"key":"独播库[飞]","name":"🛩独播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/独播库[飞].js"},
{"key":"欧帝影院[飞]","name":"🛩欧帝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧帝影院[飞].js"},
{"key":"量子影视_sq","name":"🛩量子影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/量子影视_sq(1).js"},
{"key":"煲剧吧","name":"🌎煲剧吧(量子)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/煲剧吧.js"},
{"key":"快看","name":"🌎快看(量子)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/快看.js"},
{"key":"NFM影视","name":"🌎NFM影视(量子🍭","type":3,"api":"./lib/drpy2.min.js","ext":"./js/NFM影视.js"},
{"key":"CK资源","name":"🛩CK资源♒","type":1,"api":"https://ckzy.me/api.php/provide/vod/","playUrl":"","categories":[],"searchable":1,"quickSearch":1,"filterable":1},
{"key":"CK资源(VPN)","name":"🛩CK资源(VPN)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/ck资源.js"},
{"key":"追剧啦","name":"🌎追剧啦(TK、CK)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/追剧啦(1).js"},
{"key":"天天视频","name":"🌎天天视频(CK)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/天天视频(1).js"},
{"key":"鸭奈飞","name":"🌎鸭奈飞🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/鸭奈飞.js"},
{"key":"大米星球","name":"大米星球🍭♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/大米星球(1).js"},
{"key":"歪片星球","name":"歪片星球🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/歪片星球.js"},
{"key":"奇珍异兽","name":"奇珍异兽🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"蚂蚁影视","name":"🧡蚂蚁影视(高速云)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蚂蚁影视.js"},
{"key":"碟调影视","name":"🧡碟调影视(淘片、魚樂)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/碟调影视.js"},
{"key":"看片狂人","name":"🌎看片狂人(蔚藍,量子)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看片狂人.js"},
{"key":"溪谷影视","name":"🌎溪谷影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/溪谷影视.js"},
{"key":"诺讯影视","name":"🌎诺讯影视(溪谷)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/诺讯影视.js"},
{"key":"奇优影院","name":"🌎奇优影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/奇优影院(1).js"},
{"key":"星辰","name":"🌎星辰","type":3,"api":"./lib/drpy2.min.js","ext":"./js/星辰.js"},
{"key":"小宝影视","name":"🈵🧡小宝影视(云)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小宝影视.js"},
{"key":"539影院","name":"🌎539影院","type":3,"api":"./lib/drpy2.min.js","ext":"./js/539影院.js"},
{"key":"人人影视","name":"🌎人人影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/人人影视.js"},
{"key":"8号影院","name":"🌎8号影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/8号影院.js"},
{"key":"叭度影视","name":"🌎叭度影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/叭度影视.js"},
{"key":"100影院","name":"🌎100影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/100影院.js"},
{"key":"if101[飞]","name":"🛩if101","type":3,"api":"./lib/drpy2.min.js","ext":"./js/if101[飞].js"},
{"key":"海兔影院","name":"🛩海兔影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海兔影院.js"},
{"key":"小宝影院[飞]","name":"🛩小宝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小宝影院[飞].js"},
{"key":"HoHo影视","name":"🛩HoHo影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HoHo影视.js"},
{"key":"唐人街影视[飞]","name":"🛩唐人街影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/唐人街影视[飞].js"},
{"key":"爱壹帆[飞]","name":"🛩爱壹帆🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱壹帆[飞].js"},
{"key":"大中影视[飞]","name":"🛩大中影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大中影视[飞].js"},
{"key":"金曼影视","name":"🛩金曼影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/金曼影视.js"},
{"key":"飞兔影视","name":"🛩飞兔影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/飞兔影视.js"},
{"key":"泥巴","name":"🛩泥巴🔎","type":3,"api": "csp_NiNi","searchable":1,"quickSearch":1,"filterable":1,"jar":"./FongMi_custom_spider.jar"},
{"key":"乐鱼影视","name":"💬乐鱼影视(全集)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/乐鱼影视.js"},
{"key":"回响影视","name":"🈵回响影视🔎評分","type":3,"api":"./lib/drpy2.min.js","ext":"./js/回响影视.js"},
{"key":"多瑙影视","name":"🈵多瑙影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/多瑙影视(1).js"},
{"key":"八蛋影视","name":"💬八蛋影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/八蛋影视.js"},
{"key":"影渣渣","name":"💬影渣渣","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影渣渣.js"},
{"key":"尘落影视","name":"💬尘落影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/尘落影视.js"},
{"key":"追剧喵","name":"💬追剧喵🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧喵.js"},
{"key":"喵喵","name":"💬喵喵♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/喵喵(1).js"},
{"key":"菜狗","name":"💬菜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗.js"},
{"key":"1080P","name":"🌎1080P🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/1080P.js"},
{"key":"l0l","name":"🌎l0l","type":3,"api":"./lib/drpy2.min.js","ext":"./js/l0l.js"},
{"key":"69美剧","name":"🌎69美剧🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/69美剧.js"},
{"key":"豆芽影院","name":"🌎豆芽影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆芽影院.js"},
{"key":"起飞影院","name":"🌎起飞影院","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"楚门影院","name":"🌎楚门影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/楚门影院.js"},
{"key":"艾旦影视","name":"🌎艾旦影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/艾旦影视(1).js"},
{"key":"蛋蛋赞","name":"🌎蛋蛋赞♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/蛋蛋赞(1).js"},
{"key":"蛋蛋魔法","name":"🌎蛋蛋魔法♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/蛋蛋魔法(1).js"},
{"key":"追剧达人","name":"🌎追剧达人♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/追剧达人(1).js"},
{"key":"NY影院","name":"🧡NY影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/NY影院(1).js"},
{"key":"浮生半日","name":"🌎浮生半日♒(TK)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/浮生半日(1).js"},
{"key":"子子影视","name":"子子影视♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/子子影视(1).js"},
{"key":"蜥蜴影视","name":"🌎蜥蜴影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蜥蜴影视.js"},
{"key":"在线之家Ⅱ","name":"🌎在线之家Ⅱ","type":3,"api":"./lib/drpy2.min.js","ext":"./js/在线之家Ⅱ.js"},
{"key":"看BZ影视","name":"🌎看BZ影视","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看BZ影视.js"},
{"key":"TV蜂","name":"🌎TV蜂","type":3,"api":"./lib/drpy2.min.js","ext":"./js/TV蜂.js"},
{"key":"filter_零度影视","name":"零度影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/零度影视.js"},
{"key":"filter_看看电影","name":"看看电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看看电影.js"},
{"key":"filter_我爱跟剧","name":"我爱跟剧🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/我爱跟剧.js"},
{"key":"filter_私人影院","name":"私人影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/私人影院.js"},
{"key":"filter_咕噜咕噜","name":"咕噜咕噜🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/咕噜咕噜.js"},
{"key":"filter_四个圈影视","name":"四个圈影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/四个圈影视.js"},
{"key":"filter_万博剧院","name":"万博剧院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/万博剧院.js"},
{"key":"filter_追剧兔","name":"追剧兔🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧兔.js"},
{"key":"filter_土狗影院","name":"土狗影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/土狗影院.js"},
{"key":"filter_莫扎兔","name":"莫扎兔🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/莫扎兔.js"},
{"key":"filter_凌云影视","name":"凌云影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/凌云影视.js"},
{"key":"filter_创艺影视","name":"创艺影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/创艺影视.js"},
{"key":"filter_大师兄影视","name":"大师兄影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大师兄影视.js"},
{"key":"filter_电影先生","name":"电影先生🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/电影先生.js"},
{"key":"filter_伊人追剧","name":"伊人追剧🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/伊人追剧.js"},
{"key":"filter_新视觉影视","name":"新视觉影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新视觉影视.js"},
{"key":"filter_333影视","name":"333影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/333影视.js"},
{"key":"filter_fositv","name":"fositv🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/fositv.js"},
{"key":"filter_KOK影院","name":"KOK影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KOK影院.js"},
{"key":"filter_007影视","name":"007影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/007影视.js"},
{"key":"filter_北川影视","name":"北川影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/北川影视.js"},
{"key":"filter_兄弟影视","name":"兄弟影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/兄弟影视.js"},
{"key":"filter_思古影视","name":"思古影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/思古影视.js"},
{"key":"filter_孜然影视","name":"孜然影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/孜然影视.js"},
{"key":"filter_B站影视","name":"B站影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/B站影视.js"},
{"key":"filter_嘶哩嘶哩","name":"嘶哩嘶哩🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/嘶哩嘶哩.js"},
{"key":"filter_光棍影院","name":"光棍影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/光棍影院.js"},
{"key":"filter_七年影视","name":"七年影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/七年影视.js"},
{"key":"filter_在线之家","name":"在线之家🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/在线之家.js"},
{"key":"filter_萌番","name":"萌番🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/萌番.js"},
{"key":"filter_我的哔哩","name":"我的哔哩🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/我的哔哩.js"},
{"key":"filter_布雷蓝光","name":"布雷蓝光🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/布雷蓝光.js"},
{"key":"filter_首播影院","name":"首播影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/首播影院.js"},
{"key":"filter_蓝莓影视","name":"蓝莓影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蓝莓影视.js"},
{"key":"filter_大猪蹄子","name":"大猪蹄子🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大猪蹄子.js"},
{"key":"filter_美剧网","name":"美剧网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/美剧网.js"},
{"key":"filter_量子影视","name":"量子影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/量子影视.js"},
{"key":"filter_盛世电影网","name":"盛世电影网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/盛世电影网.js"},
{"key":"filter_Voflix","name":"Voflix🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Voflix.js"},
{"key":"filter_IMAX影视","name":"IMAX影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/IMAX影视.js"},
{"key":"filter_神马影视","name":"神马影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/神马影视.js"},
{"key":"filter_花屋影院","name":"花屋影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/花屋影院.js"},
{"key":"filter_爱迪影视","name":"爱迪影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱迪影视.js"},
{"key":"filter_天空影视","name":"天空影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/天空影视.js"},
{"key":"filter_农民","name":"农民🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/农民.js"},
{"key":"filter_海外看影院","name":"海外看影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海外看影院.js"},
{"key":"filter_新思古影视","name":"新思古影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新思古影视.js"},
{"key":"filter_来看点播","name":"来看点播🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/来看点播.js"},
{"key":"filter_cokemv","name":"cokemv🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/cokemv.js"},
{"key":"filter_LIBVIO","name":"LIBVIO🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/LIBVIO.js"},
{"key":"filter_看了么","name":"看了么🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看了么.js"},
{"key":"filter_落攻阁影视","name":"落攻阁影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/落攻阁影视.js"},
{"key":"filter_爱看","name":"爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱看.js"},
{"key":"filter_饭团影视","name":"饭团影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/饭团影视.js"},
{"key":"filter_胖虎","name":"胖虎🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/胖虎.js"},
{"key":"filter_剧白白","name":"剧白白🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧白白.js"},
{"key":"filter_酷云77","name":"酷云77🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷云77.js"},
{"key":"filter_哔哩影视","name":"哔哩影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩影视.js"},
{"key":"filter_南柯电影网","name":"南柯电影网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/南柯电影网.js"},
{"key":"filter_宅腐影视2","name":"宅腐影视2🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/宅腐影视2.js"},
{"key":"filter_城市电影","name":"城市电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/城市电影.js"},
{"key":"filter_石榴影院","name":"石榴影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/石榴影院.js"},
{"key":"filter_188看","name":"188看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/188看.js"},
{"key":"filter_真不卡","name":"真不卡🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/真不卡.js"},
{"key":"filter_影视工场","name":"影视工场🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影视工场.js"},
{"key":"filter_干饭影视","name":"干饭影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/干饭影视.js"},
{"key":"filter_蓝光影院","name":"蓝光影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蓝光影院.js"},
{"key":"filter_双十电影","name":"双十电影🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/双十电影.js"},
{"key":"filter_348电影网","name":"348电影网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/348电影网.js"},
{"key":"filter_趣享星视","name":"趣享星视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/趣享星视.js"},
{"key":"filter_热播库","name":"热播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/热播库.js"},
{"key":"filter_哔嘀影视","name":"哔嘀影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔嘀影视.js"},
{"key":"filter_番茄影视","name":"番茄影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/番茄影视.js"},
{"key":"filter_AnFuns","name":"AnFuns🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AnFuns.js"},
{"key":"filter_看一看影视","name":"看一看影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看一看影视.js"},
{"key":"filter_午夜影视","name":"午夜影视🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/午夜影视.js"},
{"key":"filter_大豆","name":"大豆🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大豆.js"},
{"key":"filter_Auete","name":"Auete🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Auete.js"},
{"key":"filter_乐猪TV","name":"乐猪TV🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/乐猪TV.js"},
{"key":"filter_九酷","name":"九酷🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/九酷.js"},
{"key":"filter_骚火","name":"骚火🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/骚火.js"},
{"key":"filter_爱弹幕","name":"爱弹幕🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱弹幕.js"},
{"key":"UrleBird[飞]","name":"🛤TikTok镜像[飞]","type":3,"api":"./lib/drpy2.min.js","ext":"./js/UrleBird[飞].js"},
{"key":"JustLive","name":"🛤JustLive🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JustLive.js"},
{"key":"短视频","name":"🛤短视频","type":3,"api":"./lib/drpy2.min.js","ext":"./js/短视频.js"},
{"key":"斗鱼直播","name":"🛤斗鱼直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/斗鱼直播.js"},
{"key":"虎牙直播","name":"🛤虎牙直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/虎牙直播.js"},
{"key":"哔哩直播","name":"🛤哔哩直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩直播.js"},
{"key":"JRKAN直播","name":"🛤JRKAN直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JRKAN直播.js"},
{"key":"310直播","name":"🛤310直播","type":3,"api":"./lib/drpy2.min.js","ext":"./js/310直播.js"},
{"key":"drpy_js_Alist","name":"🧡Alist[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/alist.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/alist.json"},
{"key":"drpy_js_Alist网盘","name":"网盘|Alist[js]","type":3,"api":"./lib/alist.min.js","ext":"./js/alist.json"},
{"key":"AList","name":"网盘|Alist[jar]","type":3,"api":"csp_AList","ext":"./js/alistjar.json","jar":"./fm.jar"},
{"key":"drpy_js_Alist","name":"网盘|Alist[js]","type":3,"api":"./lib/alist.min.js","ext":"./js/alist.json"},
{"key":"纸条","name":"阿里|纸条","type":3,"api":"csp_Paper","ext":"./lib/token.txt","jar":"./fm.jar"},
{"key":"易搜","name":"阿里|易搜","type":3,"api":"csp_YiSo","ext":"./lib/token.txt","jar":"./fm.jar"},
{"key":"盘搜","name":"阿里|盘搜","type":3,"api":"csp_PanSou","ext":"./lib/token.txt","jar":"./fm.jar"},
{"key":"drpy_js_360影视","name":"官源🏛360","type":3,"api":"./lib/drpy2.min.js","ext":"./js/360影视(官).js"},
{"key":"drpy_js_奇珍异兽","name":"官源🏛爱奇艺🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇珍异兽(官).js"},
{"key":"drpy_js_优酷","name":"官源🏛优酷🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/优酷(官).js"},
{"key":"drpy_js_腾云驾雾","name":"官源🏛腾讯🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/腾云驾雾(官).js"},
{"key":"drpy_js_百忙无果","name":"官源🏛芒果🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/百忙无果(官).js"},
{"key":"drpy_js_菜狗","name":"官源🏛搜狗🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/菜狗(官).js"},
{"key":"小品网","name":"🎵小品网","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小品网.js"},
{"key":"海盗听书","name":"🎵海盗听书","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海盗听书.js"},
{"key":"爱车MV","name":"🎵爱车MV","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱车MV.js"},
{"key":"酷奇MV","name":"🎵酷奇MV","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷奇MV.js"},
{"key":"bili","name":"🎵音乐演唱","type":3,"api":"csp_Bili","ext":"./js/音乐演唱.json","jar":"./fm.jar"},
{"key":"奇米动漫","name":"🎭奇米动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/奇米动漫.js"},
{"key":"怡萱动漫","name":"🎭怡萱动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/怡萱动漫.js"},
{"key":"妮可动漫","name":"🎭妮可动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/妮可动漫.js"},
{"key":"AGE动漫","name":"🎭AGE动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AGE动漫.js"},
{"key":"动漫岛","name":"🎭动漫岛🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/动漫岛.js"},
{"key":"gaze-","name":"🎭gaze🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/gaze.js"},
{"key":"异世界动漫","name":"🎭异世界动漫🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/异世界动漫.js"},
{"key":"KUBO影视[飞]","name":"🇹🇼KUBO(繁體)","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KUBO影视[飞].js"},
{"key":"映迷影院","name":"🇹🇼映迷(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/映迷影院.js"},
{"key":"剧迷","name":"🇹🇼剧迷(繁體)🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧迷.js"},
{"key":"楓林網","name":"🇹🇼楓林網(繁體)♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/(1)/楓林網(1).js"},
{"key":"泥巴18","name":"🌈泥巴18","type":3,"api": "csp_NiNi","searchable":1,"filterable":1,"ext":"1"},
{"key":"18av","name":"🌈18av","type":3,"api":"./lib/drpy2.min.js","ext":"./js/18av.js"},
{"key":"Missav","name":"🌈Missav","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Missav.js"},
{"key":"banan","name":"🌈banan","type":3,"api":"./lib/drpy2.min.js","ext":"./js/banan.js"},
{"key":"养端","name":"🌈养端","type":3,"api":"./lib/drpy2.min.js","ext":"./js/养端.js"},
{"key":"吸瓜","name":"🌈吸瓜","type":3,"api":"./lib/drpy2.min.js","ext":"./js/吸瓜.js"},
{"key":"朱古力","name":"🌈朱古力","type":3,"api":"./lib/drpy2.min.js","ext":"./js/朱古力.js"},
{"key":"玩偶姐姐","name":"🌈玩偶姐姐","type":3,"api":"./lib/drpy2.min.js","ext":"./js/玩偶姐姐.js"},
{"key":"猫了个咪","name":"🌈猫了个咪","type":3,"api":"./lib/drpy2.min.js","ext":"./js/猫了个咪.js"},
{"key":"HD","name":"🌈HD","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HD.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源(1).txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules":[
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}],
"parses":[
{"name":"Json聚合","type":3,"url":"Demo"},
{"name":"Json并发","type":2,"url":"Parallel"},
{"name":"Json轮询","type":2,"url":"Sequence"},
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"rx2","type":1,"url":"http://rxjx.kuanjv.com/allm3u8.php?url="},
{"name":"tkys","type":1,"url":"https://rx.bt5v.com/json/jsonindex.php/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","rx","ltnb","bilibili","1905","xigua"]}},
{"name":"xifanys","type":1,"url":"http://www.pandown.pro/app/tkys/tkysjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","rx","ltnb","bilibili","1905","xigua"]}},
{"name":"酷享影视","type":1,"url":"http://pandown.pro/app/kxjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","CL4K","renrenmi","ltnb","bilibili","1905","xigua"]}},
{"name":"江湖","type":1,"url":"http://pandown.pro/app/ysmjx.php?url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905","优播线路","腾播线路"],"header":{"User-Agent":"Dart/2.14(dart:io)"}}},
{"name":"左岸","type":1,"url":"http://110.42.2.115:880/analysis/json/?uid=2100&my=cqrtwyACDGLOXY0249&mgtv=app&url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","CL4K","renrenmi","ltnb","bilibili","1905","xigua"]}},
{"name":"EXO","type":0,"url":"https://rx.69mj.com/?url=","ext":{"flag":["rx","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果"]}},
{"name":"bozrc","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":""}}},
{"name":"xmflv","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"freejson","type":0,"url":"https://h5.freejson.xyz/player/?url="},
{"name":"365","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"parwix稳定","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"parwix1","type":0,"url":"https://jx.parwix.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"夜幕","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"1-26db","type":0,"url":"http://vip.26db.cn/g/?url="},
{"name":"2-小猫咪","type":0,"url":"http://player.xmmi.xyz/player/?url="},
{"name":"3-看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"4-FreeOK","type":0,"url":"https://play.86516.tk/OKPlayer/?url="},
{"name":"5-虾米","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"6-麒麟","type":0,"url":"https://www.cygqw.com/jiexi/jiekou-2/?url="},
{"name":"7-parwix1","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"8-OK解析","type":0,"url":"http://okjx.cc/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"10-m3u8tv","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"11-鸿途PCUA","type":0,"url":"https://h5.freejson.xyz/player/?url="},
{"name":"8090","type":0,"url":"https://www.8090g.cn/?url="},
{"name":"解析第一","type":0,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url="},
{"name":"解析05","type":0,"url":"http://id190.tpddns.cn:81/jsonch/?url="},
{"name":"m3u8tv高清","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="},
{"name":"OKjx综合","type":0,"url":"https://okjx.cc/?url="},
{"name":"爱酷嗅探","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"Webè§£æ��","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["youku","ä¼˜é…·","mgtv","èŠ’æ�œ","qq","è…¾è®¯","qiyi","çˆ±å¥‡è‰º","iqiyi","å¥‡è‰º"]}},
{"name":"zui","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"ltnb04","type":0,"url":"https://vip.bljiex.com/?v=","ext":{"flag":["ltnb"]}},
{"name":"ğŸ’‹Soä¸¶","type":0,"url":"https://tljiaqing.nde.tw/m3u8/?url="},
{"name":"ç¥�2","type":0,"url":"https://h5.freejson.xyz/player/?url=","ext":{"flag":["qq","è…¾è®¯","qiyi","çˆ±å¥‡è‰º","å¥‡è‰º","youku","ä¼˜é…·","mgtv","èŠ’æ�œ","letv","ä¹�è§†","pptv","PPTV","sohu","bilibili","å“”å“©å“”å“©","å“”å“©"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name":"ç¥�4","type":0,"url":"https://freejx.rx88.top:1234/?url="},
{"name":"rx2","type":1,"url":"http://rxjx.kuanjv.com/allm3u8.php?url="},
{"name":"风起清河","type":1,"url":"http://www.pandown.pro/app/tkys/tkysjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","rx","ltnb","bilibili","1905","xigua"]}},
{"name":"风起陈留","type":1,"url":"http://pandown.pro/app/ysmjx.php?url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905","优播线路","腾播线路"],"header":{"User-Agent":"Dart/2.14(dart:io)"}}},
{"name":"风起陇西1","type":0,"url":"https://hxys.tv/bfq/?url="},
{"name":"风起兖州","type":0,"url":"http://jx.gbxy.net.cn/?url="},
{"name":"灵谷","type":1,"url":"http://s.lingutv.cn/?url=","ext":{"flag":["qiyi","iqiyi","奇艺","爱奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果","xigua","西瓜","sohu","搜狐","cntv","cctv","央视","1905","m1905"]}},
{"name":"ç›˜å�¤","type":0,"url":"https://www.m3u8.tv.cdn.8old.cn/jx.php?url="},
{"name":"H8","type":0,"url":"https://www.h8jx.com/jiexi.php?url="},
{"name":"思古3","type":0,"url":"https://jsap.attakids.com/?url="},
{"name":"云端1","type":0,"url":"https://js.52jx.top:2525/?url="},
{"name":"云端2","type":0,"url":"https://sb.5gseo.net/?url="},
{"name":"Web4","type":0,"url":"https://dm.xmflv.com:4433/?url=","ext":{"flag":["imgo","ltnb","renrenmi","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩"]}},
{"name":"Web5","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["imgo","qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"Json9","type":1,"url":"http://jx.vipmv.co/json.php?token=123457&url=","ext":{"flag":["qq","腾讯","letv","乐视","mgtv","芒果","youku","优酷","qiyi","iqiyi","爱奇艺","奇艺"]}},
{"name":"Web6","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name":"左岸","url":"https://jx.bozrc.com:4433/player/analysis.php?v=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"91","url":"http://91fanli.top/m3u8/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"全民1","url":"http://api.wpsseo.cn/?v=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"8090","url":"https://www.8090.la/8090/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"365","url":"https://chaxun.Truechat365.com/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"m2090","url":"https://m2090.com/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"解析14","url":"https://go.yh0523.cn/y.cy?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"解析la","url":"https://api.jiexi.la/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"PM","url":"https://www.playm3u8.cn/jiexi.php?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"盘古","url":"https://www.pangujiexi.cc/jiexi.php?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"全民","url":"https://jx.blbo.cc:4433/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"云析","url":"https://jx.yparse.com/index.php?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"180","url":"https://jx.000180.top/jx/?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"1717云","url":"https://www.1717yun.com/jx/ty.php?url=","type":0,"ext":{"flag":["qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"],"header":{"User-Agent":"Mozilla/5.0"}},"header":{"User-Agent":"Mozilla/5.0"}},
{"name":"道长VIP","type":1,"url":"https://80k.tv/jxplayer.php?v="}],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg"
}