//./jshttp.js
{
"spider":"./top98_1.jar",
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"豆瓣","name":"豆瓣2🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"7喜影院","name":"🛩7喜影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/7喜影院.js"},
{"key":"欧乐影院","name":"🛩歐樂影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧乐影院.js"},
{"key":"独播库","name":"🛩独播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/独播库.js"},
{"key":"欧帝影院","name":"🛩欧帝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"美视网","name":"🌎美视网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/美视网.js"},
{"key":"起飞影院","name":"🌎起飞影院💬","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"大米星球","name":"🌎大米星球(量)🍭♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大米星球.js"},
{"key":"filter_骚火.js","name":"骚火.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/骚火.js"},
{"key":"filter_九酷.js","name":"九酷.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/九酷.js"},
{"key":"filter_乐猪TV.js","name":"乐猪TV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/乐猪TV.js"},
{"key":"filter_Auete.js","name":"Auete.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Auete.js"},
{"key":"filter_午夜影视.js","name":"午夜影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/午夜影视.js"},
{"key":"filter_看一看影视.js","name":"看一看影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看一看影视.js"},
{"key":"filter_看韩剧.js","name":"看韩剧.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看韩剧.js"},
{"key":"filter_酷客影院.js","name":"酷客影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷客影院.js"},
{"key":"filter_AnFuns.js","name":"AnFuns.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AnFuns.js"},
{"key":"filter_荐片.js","name":"荐片.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/荐片.js"},
{"key":"filter_哔嘀影视.js","name":"哔嘀影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔嘀影视.js"},
{"key":"filter_路漫漫.js","name":"路漫漫.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/路漫漫.js"},
{"key":"filter_91free.js","name":"91free.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/91free.js"},
{"key":"filter_番茄影视.js","name":"番茄影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/番茄影视.js"},
{"key":"filter_趣享星视.js","name":"趣享星视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/趣享星视.js"},
{"key":"filter_AB影院.js","name":"AB影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AB影院.js"},
{"key":"filter_在线之家.js","name":"在线之家.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/在线之家.js"},
{"key":"filter_萌番.js","name":"萌番.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/萌番.js"},
{"key":"filter_348电影网.js","name":"348电影网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/348电影网.js"},
{"key":"filter_万能影视.js","name":"万能影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/万能影视.js"},
{"key":"filter_LIBVIO.js","name":"LIBVIO.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/LIBVIO.js"},
{"key":"filter_柒之社.js","name":"柒之社.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/柒之社.js"},
{"key":"filter_蓝光影院.js","name":"蓝光影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蓝光影院.js"},
{"key":"filter_干饭影视.js","name":"干饭影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/干饭影视.js"},
{"key":"filter_影视工场.js","name":"影视工场.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影视工场.js"},
{"key":"filter_188看.js","name":"188看.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/188看.js"},
{"key":"filter_嘶哩嘶哩.js","name":"嘶哩嘶哩.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/嘶哩嘶哩.js"},
{"key":"filter_石榴影院.js","name":"石榴影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/石榴影院.js"},
{"key":"filter_zxzjmtv.js","name":"zxzjmtv.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/zxzjmtv.js"},
{"key":"filter_城市电影.js","name":"城市电影.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/城市电影.js"},
{"key":"filter_两个BT.js","name":"两个BT.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/两个BT.js"},
{"key":"filter_B站影视.js","name":"B站影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/B站影视.js"},
{"key":"filter_南柯电影网.js","name":"南柯电影网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/南柯电影网.js"},
{"key":"filter_宅腐影视2.js","name":"宅腐影视2.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/宅腐影视2.js"},
{"key":"filter_思古影视.js","name":"思古影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/思古影视.js"},
{"key":"filter_哔哩影视.js","name":"哔哩影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩影视.js"},
{"key":"filter_哔哩兔.js","name":"哔哩兔.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/哔哩兔.js"},
{"key":"filter_剧白白.js","name":"剧白白.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧白白.js"},
{"key":"filter_酷云77.js","name":"酷云77.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷云77.js"},
{"key":"filter_北川影视.js","name":"北川影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/北川影视.js"},
{"key":"filter_胖虎.js","name":"胖虎.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/胖虎.js"},
{"key":"filter_曲奇动漫.js","name":"曲奇动漫.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/曲奇动漫.js"},
{"key":"filter_量子影视_sq.js","name":"量子影视_sq.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/量子影视_sq.js"},
{"key":"filter_007影视.js","name":"007影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/007影视.js"},
{"key":"filter_KOK影院.js","name":"KOK影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KOK影院.js"},
{"key":"filter_落攻阁影视.js","name":"落攻阁影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/落攻阁影视.js"},
{"key":"filter_神马影视.js","name":"神马影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/神马影视.js"},
{"key":"filter_看了么.js","name":"看了么.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看了么.js"},
{"key":"filter_333影视.js","name":"333影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/333影视.js"},
{"key":"filter_追剧兔.js","name":"追剧兔.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧兔.js"},
{"key":"filter_新视觉影视.js","name":"新视觉影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新视觉影视.js"},
{"key":"filter_来看点播.js","name":"来看点播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/来看点播.js"},
{"key":"filter_素白白.js","name":"素白白.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/素白白.js"},
{"key":"filter_农民.js","name":"农民.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/农民.js"},
{"key":"filter_新思古影视.js","name":"新思古影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新思古影视.js"},
{"key":"filter_fositv.js","name":"fositv.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/fositv.js"},
{"key":"filter_农民影视.js","name":"农民影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/农民影视.js"},
{"key":"filter_大豆.js","name":"大豆.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大豆.js"},
{"key":"filter_兄弟影视.js","name":"兄弟影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/兄弟影视.js"},
{"key":"filter_电影先生.js","name":"电影先生.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/电影先生.js"},
{"key":"filter_Fun4K.js","name":"Fun4K.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Fun4K.js"},
{"key":"filter_爱迪影视.js","name":"爱迪影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱迪影视.js"},
{"key":"filter_稀饭影视.js","name":"稀饭影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/稀饭影视.js"},
{"key":"filter_莫扎兔.js","name":"莫扎兔.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/莫扎兔.js"},
{"key":"filter_咕噜咕噜.js","name":"咕噜咕噜.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/咕噜咕噜.js"},
{"key":"filter_去看吧.js","name":"去看吧.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/去看吧.js"},
{"key":"filter_无名小站.js","name":"无名小站.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/无名小站.js"},
{"key":"filter_Voflix.js","name":"Voflix.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Voflix.js"},
{"key":"filter_花屋影院.js","name":"花屋影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/花屋影院.js"},
{"key":"filter_IMAX影视.js","name":"IMAX影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/IMAX影视.js"},
{"key":"filter_伊人追剧.js","name":"伊人追剧.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/伊人追剧.js"},
{"key":"filter_盛世电影网.js","name":"盛世电影网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/盛世电影网.js"},
{"key":"filter_冷曦影视.js","name":"冷曦影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/冷曦影视.js"},
{"key":"filter_六度TV.js","name":"六度TV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/六度TV.js"},
{"key":"filter_小猫咪.js","name":"小猫咪.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小猫咪.js"},
{"key":"filter_美剧网.js","name":"美剧网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/美剧网.js"},
{"key":"filter_万博剧院.js","name":"万博剧院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/万博剧院.js"},
{"key":"filter_私人影院.js","name":"私人影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/私人影院.js"},
{"key":"filter_模板.js","name":"模板.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/模板.js"},
{"key":"filter_爱看.js","name":"爱看.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱看.js"},
{"key":"filter_看看电影.js","name":"看看电影.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看看电影.js"},
{"key":"filter_伊雪湾.js","name":"伊雪湾.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/伊雪湾.js"},
{"key":"filter_大猪蹄子.js","name":"大猪蹄子.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大猪蹄子.js"},
{"key":"filter_天空影视.js","name":"天空影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/天空影视.js"},
{"key":"filter_蓝莓影视.js","name":"蓝莓影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蓝莓影视.js"},
{"key":"filter_零度影视.js","name":"零度影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/零度影视.js"},
{"key":"filter_免费看.js","name":"免费看.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/免费看.js"},
{"key":"filter_首播影院.js","name":"首播影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/首播影院.js"},
{"key":"filter_布雷蓝光.js","name":"布雷蓝光.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/布雷蓝光.js"},
{"key":"filter_我的哔哩.js","name":"我的哔哩.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/我的哔哩.js"},
{"key":"filter_粤爱看","name":"🇭🇰粤爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/粤爱看.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules":[
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}],
"parses":[
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"猫爪","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"ok","type":0,"url":"https://okjx.cc/?url="},
{"name":"bozrc","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":""}}},
{"name":"不累","type":0,"url":"https://blbfq.f3322.net/player/analysis.php?v=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"cod","type":0,"url":"https://ksksl.codjx.com/?url="},
{"name":"byg解析","type":0,"url":"https://byg.ziqj5.shop/?url="},
{"name":"xmflv","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"365","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"26db","type":0,"url":"http://vip.26db.cn/g/?url="},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"FreeOK","type":0,"url":"https://play.86516.tk/OKPlayer/?url="},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url="}],
"ads": ["https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd","mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg"
}