{
"spider":"./custom_spider.jar",
"sites" : [
{"key":"lf_js_search","name":"🔎搜索影片　　　　🔥祝大家🤩好運🐉總來💯","type":3,"searchable":0,"changeable":1,"quickSearch":0,"filterable":0,"api":"./lib/lf_search3_min.js","ext":"18+"},
{"key":"drpy","name":"豆瓣","type":3,"api":"drpy2.min.js","ext":"./js/豆瓣.js"},
//{"key":"drpy2","name":"豆瓣2🍭","type":3,"api":"drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy__豆瓣","name":"豆瓣🏛[DRPY]","type":3,"api":"drpy2.min.js","ext":"https://raw.githubusercontent.com/hjdhnx/dr_py/main/js/drpy.js"},
{"key":"ikanbotsq","name":"🈵爱看机器人sq","type":3,"api":"drpy2.min.js","ext":"./js/ikanbotsq.js"},
{"key":"农民","name":"💬評分 農民","type":3,"api":"drpy2.min.js","ext":"./js/农民影视.js"},
{"key":"一起看","name":"💬評分/集數 一起看","type":"3","api":"csp_Dora","changeable":"0","searchable":"1","quickSearch":"1","filterable":"1","ext":"8e3aefcba838d8dc5102ac786719d837","jar":"./t.jar"},
{ "key": "YQKan", "name": "🔥一起看APP", "type": 3, "api": "csp_YQKan", "searchable": 1, "quickSearch": 1, "filterable": 1, "changeable": 1 ,"jar":"./pg.jar"},
{"key":"乐鱼影视","name":"💬集數 乐鱼影视","type":3,"api":"drpy2.min.js","ext":"./js/乐鱼影视.js"},
{"key":"T4-安博","name":"🔥安博(T4)","type":4,"api":"https://tang.serv00.net/power/ub1818","searchable":1,"quickSearch":1,"filterable":1,"changeable":0,"ext":true},
{"key":"独播库","name":"🔥独播库","type":3,"api":"drpy2.min.js","ext":"./js/独播库[飞].js","playerType":"1"},
{"key":"duboku","name":"🔥独播库js","type":3,"api":"drpy2.min.js","ext":"./js/duboku.json","playerType":"1"},
{"key":"csp_XP_独播库","name":"🔥独播库[XPMF]","type":3,"api":"csp_XPathMacFilter","playerType":0,"searchable":1,"quickSearch":1,"filterable":1,"ext":"./js/duboku.json"},
{"key":"海外看网","name":"🔥海外看haiwaikan","type":0,"api":"https://haiwaikan.com/api.php/provide/vod/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"oletv資源f","name":"🔥oletv資源(海外)","type":1,"api":"https://olevod1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"非凡网","name":"🔥非凡ff","type":0,"api":"http://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快看网","name":"🔥快看kk","type":0,"api":"https://kuaikan-api.com/api.php/provide/vod/at/xmlsea","searchable":1,"quickSearch":1,"filterable":1},
{"key":"優質网","name":"🔥優質zyk","type":0,"api":"https://api.1080zyku.com/inc/api.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"索尼","name":"🔥索尼sn","type":1,"api":"https://suoniapi.com/api.php/provide/vod","searchable":1,"quickSearch":1,"filterable":1},
{"key":"索尼2","name":"🔥索尼2","type":0,"api":" https://suoniapi.com/api.php/provide/vod/from/snm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"天空网","name":"🔥天空tk","type":0,"api":"https://api.tiankongapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"欧帝影院","name":"🔥欧帝影院","type":3,"api":"drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"泥巴","name":"🔥泥巴","type":3,"api":"csp_Nbys","searchable":1,"filterable":1,"jar":"./top98_1.jar"},
{"key":"豪华","name":"🌅豪华hh","type":0,"api":"https://hhzyapi.com/api.php/provide/vod/from/hhm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"欧乐影院","name":"🌅歐樂影院♒","type":3,"api":"drpy2.min.js","ext":"./js/欧乐影院.js"},
{"key":"奇虎影视e","name":"🌅奇虎影视qz","type":1,"api":"https://caiji.qhzyapi.com/api.php/provide/vod/from/qhm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"飛速网","name":"🌅飛速fe","type":0,"api":"https://www.feisuzyapi.com/api.php/provide/vod/from/fsm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"ikun网","name":"🏆ikun","type":0,"api":"https://ikunzyapi.com/api.php/provide/vod/from/ikm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"暴风影视","name":"🏆暴风bf","type":1,"api":"https://bfzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"大漠影视e","name":"🏆大漠dm","type":1,"api":"https://damozy.com/api.php/provide/vod/from/M3U8/","searchable":1,"quickSearch":1,"filterable":1},
{"key": "种子","name": "🏆种子短剧zz","type": 1,"api": "http://zzdj.cc/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"filterable": 1},
{"key":"量子網","name":"🏆量子lz","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"categories":["国产剧","国产动漫","泰国剧","台湾剧","香港剧","欧美剧","韩国剧","日本剧","动漫","体育","剧情片","动作片","爱情片","喜剧片"]},
{"key":"U酷網","name":"🏆U酷","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"红牛","name":"🏆红牛hn","type":0,"api":"https://www.hongniuzy2.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"八戒网","name":"🏆八戒bj","type":1,"api":"http://cj.bajiecaiji.com/inc/apijson_vod.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"drpy_js_360影视","name":"官源🏛360","type":3,"api":"drpy2.min.js","ext":"./js/360影视.js"},
{"key":"drpy_js_百忙无果","name":"官源🏛芒果","type":3,"api":"drpy2.min.js","ext":"./js/百忙无果.js"},
{"key":"drpy_js_奇珍异兽","name":"官源🏛爱奇艺🍭","type":3,"api":"drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"drpy_js_腾云驾雾","name":"官源🏛腾讯","type":3,"api":"drpy2.min.js","ext":"./js/腾云驾雾.js"},
{"key":"drpy_js_优酷","name":"官源🏛优酷","type":3,"api":"drpy2.min.js","ext":"./js/优酷.js"},
{"key": "csp_Alist1_cj1","name": "☁Alist1️⃣┃网盘","type": 3,"api": "csp_AList","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0,"jar":"./pg.jar","ext":"./js/18cj_alist1.json"},
{"key": "csp_Alist1_cj2","name": "☁Alist🕑┃网盘","type": 3,"api": "csp_AList","searchable": 1,"quickSearch": 0,"filterable": 0,"changeable": 0,"jar":"./pg.jar","ext":"./js/18cj_alist2.json"},
{"key":"快播網","name":"🌟快播kb","type":1,"api":"http://www.kuaibozy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"樱花網","name":"🌟樱花yh","type":1,"api":"https://m3u8.apiyhzy.com/api.php/provide/vod/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"68网","name":"🌟6868","type":0,"api":"https://caiji.68zyapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"if101","name":"🌟if101","type":3,"api":"drpy2.min.js","ext":"./js/if101.js"},
{"key":"淘片网","name":"🌕淘片tp","type":0,"api":"https://taopianapi.com/home/cjapi/as/mc/vod/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"易看","name":"🌕易看♒yk","api":"https://api.yikanapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"新浪","name":"🌕新浪xl","type":0,"api":"https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"鱼乐網","name":"🌕鱼乐le","type":1,"api":"https://api.ylzy1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鷹网","name":"🌕金鷹jyz","type":0,"api":"https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快车網","name":"😰快车kc","type":1,"api":"https://caiji.kczyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"CK采集网","name":"😰CK采集网","type":1,"api":"https://ckzy.me/api.php/provide/vod/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"CK(VPN)","name":"🛩CK(VPN)","type":3,"api":"drpy2.min.js","ext":"./js/ck.js"},
{"key":"极速影视e","name":"😰极速影视jz","type":1,"api":"https://jszyapi.com/api.php/provide/vod/from/jsm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"taopian資源f","name":"😰taopian資源(淘片)","type":1,"api":"https://taopianapi.com/cjapi/mc/vod/json/m3u8.html","searchable":1,"quickSearch":1,"filterable":1},
//{"key":"快帆","name":"快帆","type":1,"api":"https://api.kuaifan.tv/api.php/provide/vod","searchable":1,"quickSearch":1,"filterable":1},
{"key":"UM电影[V2]","name":"UM电影[V2]🏆索尼","type":3,"api":"drpy.min.js","ext":"./js/UM电影[V2].js"},
{"key":"555影视[V2]","name":"555影视[V2]🏆大漠","type":3,"api":"drpy2.min.js","ext":"./js/555影视[V2].js"},
{"key":"宝片[V2]","name":"宝片[V2]🏆种子","type":3,"api":"drpy.min.js","ext":"./js/宝片[V2].js"},
{"key":"起飞影院","name":"起飞影院","type":3,"api":"drpy.min.js","ext":"./js/起飞影院.js"},
{"key":"北极狐[V2]","name":"北极狐[V2]","type":3,"api":"drpy.min.js","ext":"./js/北极狐[V2].js"},
{"key":"多瑙影视","name":"🈵多瑙影视♒","type":3,"api":"drpy2.min.js","ext":"./js/多瑙影视.js"},
{"key":"厂长","name":"🎯厂长","type":3,"api":"drpy2.min.js","ext":"./js/厂长.js"},
{"key":"电影先生","name":"🎯电影先生","type":3,"api":"drpy2.min.js","ext":"./js/电影先生.js"},
{"key":"南瓜影视","name":"🎯南瓜影视","type":3,"api":"drpy2.min.js","ext":"./js/南瓜影视.js"},
{"key":"77韩剧","name":"🌕77韩剧","api":"https://www.77hanju.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"韩剧","name":"🌕韩剧","api":"http://www.hanjuzy.com/inc/apijson_vod.php","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"shoujihanju資源f","name":"🌕shoujihanju(韓劇)","type":1,"api":"https://77hanju.com/api.php/provide/vod/from/mkm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"路人甲[V2]","name":"路人甲[V2]","type":3,"api":"drpy.min.js","ext":"./js/路人甲[V2].js"},
{"key":"落攻阁影视[V2]","name":"落攻阁影视[V2]","type":3,"api":"drpy.min.js","ext":"./js/落攻阁影视[V2].js"},
{"key":"短剧网","name":"短剧网","type":3,"api":"drpy.min.js","ext":"./js/短剧网.js"},
{"key":"电影先生","name":"电影先生","type":3,"api":"drpy.min.js","ext":"./js/电影先生.js"},
{"key":"歪片星球","name":"歪片星球","type":3,"api":"drpy.min.js","ext":"./js/歪片星球.js"},
{"key":"思古影视[V2]","name":"思古影视[V2]","type":3,"api":"drpy.min.js","ext":"./js/思古影视[V2].js"},
{"key":"奇珍异兽","name":"奇珍异兽","type":3,"api":"drpy.min.js","ext":"./js/奇珍异兽.js"},
{"key":"华乐影院","name":"华乐影院","type":3,"api":"drpy.min.js","ext":"./js/华乐影院.js"},
{"key":"农民影视","name":"农民影视","type":3,"api":"drpy.min.js","ext":"./js/农民影视.js"},
{"key":"优酷","name":"优酷","type":3,"api":"drpy.min.js","ext":"./js/优酷.js"},
{"key":"NY影院","name":"NY影院","type":3,"api":"drpy.min.js","ext":"./js/NY影院.js"},
{"key":"532影院[V2]","name":"532影院[V2]","type":3,"api":"drpy.min.js","ext":"./js/532影院[V2].js"},
{"key":"毛子[V2]","name":"毛子[V2]","type":3,"api":"drpy.min.js","ext":"./js/毛子[V2].js"},
{"key":"刺桐[V2]","name":"刺桐[V2]","type":3,"api":"drpy.min.js","ext":"./js/刺桐[V2].js"},
{"key":"佳靓[V2]","name":"佳靓[V2]","type":3,"api":"drpy.min.js","ext":"./js/佳靓[V2].js"},
{"key":"百度网","name":"🏆百度db","type":0,"api":"https://api.apibdzy.com/api.php/provide/vod/from/dbm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
//{"key":"FOX","name":"😰FOXfox","type":1,"api":"https://api.foxzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
//{"key":"光速","name":"😰光速gs","type":0,"api":"https://api.guangsuapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"速影","name":"😰速影動漫wj","type":1,"api":"https://速影128.xyz/inc/apijson.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"闪电","name":"😰闪电sd","type":1,"api":"http://sdzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鹰影视e","name":"😰金鹰影视","type":1,"api":"https://jinyingzy.com/provide/vod/from/jinyingm3u8/","searchable":1,"quickSearch":1,"filterable":1},
//{"key":"酷点网","name":"😰酷点网kd","type":0,"api":" https://kudian10.com/api.php/provide/vod/from/kdm3u8/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"无尽网","name":"🌟无尽wj","type":0,"api":"https://api.wujinapi.me/api.php/provide/vod/from/wjm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
//{"key":"阳光","name":"😰阳光","type":0,"api":"https://xxzy.org/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"7喜影院","name":"🛩7喜影院♒","type":3,"api":"drpy2.min.js","ext":"./js/7喜影院.js"},
{"key":"爱看机器人","name":"爱看机器人1","type":3,"api":"drpy2.min.js","ext":"./js/爱看机器人.js"},
{"key":"小宝影视","name":"🈵☁小宝影视","type":3,"api":"drpy2.min.js","ext":"./js/小宝影视.js"},
{"key":"回响影视","name":"🈵回响影视評分","type":3,"api":"drpy2.min.js","ext":"./js/回响影视.js"},
{"key":"真不卡","name":"🈵☁真不卡","type":3,"api":"drpy2.min.js","ext":"./js/真不卡.js"},
{"key":"飞兔影视js","name":"飞兔影视♒","type":3,"api":"drpy.min.js","ext":"./js/飞兔影视.js"},
{"key":"金曼影视js","name":"金曼影视♒","type":3,"api":"drpy.min.js","ext":"./js/金曼影视.js"},
{"key":"量子影视js","name":"量子影视♒","type":3,"api":"drpy.min.js","ext":"./js/量子影视.js","playerType":"1"},
{"key":"酷云77js","name":"酷云77♒","type":3,"api":"drpy.min.js","ext":"./js/酷云77.js"},
{"key":"蜥蜴影视js","name":"蜥蜴影视♒","type":3,"api":"drpy.min.js","ext":"./js/蜥蜴影视.js"},
{"key":"纽约影院js","name":"纽约影院♒","type":3,"api":"drpy.min.js","ext":"./js/纽约影院.js"},
{"key":"磁力熊[磁]js","name":"磁力熊[磁]♒","type":3,"api":"drpy.min.js","ext":"./js/磁力熊[磁].js"},
{"key":"电影先生[V2]js","name":"电影先生[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/电影先生[V2].js"},
{"key":"爱迪影视js","name":"爱迪影视♒","type":3,"api":"drpy.min.js","ext":"./js/爱迪影视.js"},
{"key":"爱迪[V2]js","name":"爱迪[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/爱迪[V2].js"},
{"key":"朴樱影视js","name":"朴樱影视♒","type":3,"api":"drpy.min.js","ext":"./js/朴樱影视.js"},
{"key":"我爱跟剧js","name":"我爱跟剧♒","type":3,"api":"drpy.min.js","ext":"./js/我爱跟剧.js"},
{"key":"思古影视js","name":"思古影视♒","type":3,"api":"drpy.min.js","ext":"./js/思古影视.js"},
{"key":"布雷蓝光[V2]js","name":"布雷蓝光[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/布雷蓝光[V2].js"},
{"key":"小狗影院js","name":"小狗影院♒","type":3,"api":"drpy.min.js","ext":"./js/小狗影院.js"},
{"key":"子子影视js","name":"子子影视♒","type":3,"api":"drpy.min.js","ext":"./js/子子影视.js"},
{"key":"奇珍异兽js","name":"奇珍异兽♒","type":3,"api":"drpy.min.js","ext":"./js/奇珍异兽.js"},
{"key":"多瑙影视js","name":"多瑙影视♒","type":3,"api":"drpy.min.js","ext":"./js/多瑙影视.js"},
{"key":"厂长js","name":"厂长♒","type":3,"api":"drpy.min.js","ext":"./js/厂长.js"},
{"key":"华乐影院js","name":"华乐影院♒","type":3,"api":"drpy.min.js","ext":"./js/华乐影院.js"},
{"key":"北极狐[V2]js","name":"北极狐[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/北极狐[V2].js"},
{"key":"优酷js","name":"优酷♒","type":3,"api":"drpy.min.js","ext":"./js/优酷.js"},
{"key":"两个BTjs","name":"两个BT♒","type":3,"api":"drpy.min.js","ext":"./js/两个BT.js"},
{"key":"UM电影[V2]js","name":"UM电影[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/UM电影[V2].js"},
{"key":"NY影院js","name":"NY影院♒","type":3,"api":"drpy.min.js","ext":"./js/NY影院.js"},
{"key":"gazejs","name":"gaze♒","type":3,"api":"drpy.min.js","ext":"./js/gaze.js"},
{"key":"EMO蓝光[V2]js","name":"EMO蓝光[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/EMO蓝光[V2].js"},
{"key":"7喜影院js","name":"7喜影院♒","type":3,"api":"drpy.min.js","ext":"./js/7喜影院.js"},
{"key":"69美剧js","name":"69美剧♒","type":3,"api":"drpy.min.js","ext":"./js/69美剧.js"},
{"key":"4K电影网js","name":"4K电影网♒","type":3,"api":"drpy.min.js","ext":"./js/4K电影网.js"},
{"key":"360影视js","name":"360影视♒","type":3,"api":"drpy.min.js","ext":"./js/360影视.js"},
{"key":"天空影视js","name":"天空影视♒","type":3,"api":"drpy.min.js","ext":"./js/天空影视.js"},
{"key":"星空影视js","name":"星空影视♒","type":3,"api":"drpy.min.js","ext":"./js/星空影视.js"},
{"key":"萌蛋蛋[V2]js","name":"萌蛋蛋[V2]♒","type":3,"api":"drpy.min.js","ext":"./js/萌蛋蛋[V2].js"},
{"key":"ikanbot2","name":"爱看机器人2","type":3,"api":"drpy2.min.js","ext":"./js/ikanbot2.js"},
{"key":"ikanbot3","name":"爱看机器人3","type":3,"api":"drpy2.min.js","ext":"./js/ikanbot3.js"}
],
"lives":[{"name":"自選","type":0,"url":"./live.txt","epg":"https://epg.112114.xyz/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"}],
//"doh":[{"name":"Google","url":"https://dns.google/dns-query","ips":["8.8.4.4","8.8.8.8"]},{"name":"Cloudflare","url":"https://cloudflare-dns.com/dns-query","ips":["1.1.1.1","1.0.0.1","2606:4700:4700::1111","2606:4700:4700::1001"]},{"name":"AdGuard","url":"https://dns.adguard.com/dns-query","ips":["94.140.14.140","94.140.14.141"]},{"name":"DNSWatch","url":"https://resolver2.dns.watch/dns-query","ips":["84.200.69.80","84.200.70.40"]},{"name":"Quad9","url":"https://dns.quad9.net/dns-quer","ips":["9.9.9.9","149.112.112.112"]}],
//"rules":[{"name":"proxy","hosts":["raw.githubusercontent.com","googlevideo.com","cdn.v82u1l.com","cdn.iz8qkg.com","cdn.kin6c1.com","c.biggggg.com","c.olddddd.com","haiwaikan.com","www.histar.tv","youtube.com","uhibo.com",".*boku.*",".*nivod.*",".*ulivetv.*"]},{"name":"海外看","hosts":["haiwaikan"],"regex":["10.0099","10.3333","16.0599","8.1748","10.85"]},{"name":"索尼","hosts":["suonizy"],"regex":["15.1666","15.2666","16.333333"]},{"name":"暴風","hosts":["bfzy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},{"name":"星星","hosts":["aws.ulivetv.net"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:8,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},{"name":"量子","hosts":["vip.lz","hd.lz","v.cdnlz"],"regex":["18.5333"]},{"name":"非凡","hosts":["vip.ffzy","hd.ffzy"],"regex":["25.0666"]},{"name":"火山嗅探","hosts":["huoshan.com"],"regex":["item_id="]},{"name":"抖音嗅探","hosts":["douyin.com"],"regex":["is_play_url="]},{"name":"農民嗅探","hosts":["toutiaovod.com"],"regex":["video/tos/cn"]}],
//"rules":[{"name":"星星","hosts":["aws.ulivetv.net"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:8,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},{"name":"量子廣告","hosts":["vip.lz","hd.lz"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.433333,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},{"name":"非凡廣告","hosts":["vip.ffzy","hd.ffzy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.666667,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"]},{"name":"火山嗅探","hosts":["huoshan.com"],"regex":["item_id="]},{"name":"抖音嗅探","hosts":["douyin.com"],"regex":["is_play_url="]},{"host":"*","rule":["http((?!http).){12,}?\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)\\?.*"]},{"host":"*","rule":["http((?!http).){12,}\\.(m3u8|mp4|flv|avi|mkv|rm|wmv|mpg|m4a)"]},{"name":"農民嗅探","hosts":["toutiaovod.com"],"regex":["video/tos/cn"]}],
//"rules":[{"name":"海外看","hosts":["haiwaikan"],"regex":["10.0099","10.3333","16.0599","8.1748","10.85"]},{"name":"索尼","hosts":["suonizy"],"regex":["15.1666","15.2666","16.333333"]},{"name":"暴風","hosts":["bfzy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},{"name":"量子","hosts":["vip.lz","hd.lz","v.cdnlz"],"regex":["18.5333"]},{"name":"非凡","hosts":["vip.ffzy","hd.ffzy"],"regex":["25.0666"]}],
"parses":[
{"name":"777","type":0,"url":"https://jx.777jiexi.com/player/?url="},
{"name":"杰森","type":0,"url":"https://jx.jsonplayer.com/player/?url="}, 
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"A01","type":0,"url":"http://api.apii.top/?v="},
{"name":"A05","type":0,"url":"http://www.wpsseo.cn/line.php?n=7&url="},
{"name":"A12","type":0,"url":"https://jx.quankan.app/?url="},
{"name":"A14","type":0,"url":"https://www.pangujiexi.com/pangu/?url="},
{"name":"9号线","url":"https://www.8090g.cn/?url="},
{"name":"12号线","type":0,"url":"https://jx.m3u8.tv/jiexi/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"17号线","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"👉嗅探👈就是破解中，請等候一會👈","type":0,"url":"http://pandown.pro/app/ysmjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}}],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg",
"ads":["mozai.4gtv.tv"]

}