//./jshttp.js
{
"spider":"./top98_1.jar",
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"豆瓣","name":"豆瓣2🍭🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy_js_豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/lib/drpy2.min.js","ext":"https://agit.ai/138001380000/MHQTV/raw/branch/master/js/js/drpy.js"},
{"key":"7喜影院","name":"🛩7喜影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/7喜影院.js"},
{"key":"欧乐影院","name":"🛩歐樂影院♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧乐影院.js"},
{"key":"独播库","name":"🛩独播库🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/独播库.js"},
{"key":"欧帝影院","name":"🛩欧帝影院🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"美视网","name":"🌎美视网🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/美视网.js"},
{"key":"起飞影院","name":"🌎起飞影院💬","type":3,"api":"./lib/drpy2.min.js","ext":"./js/起飞影院.js"},
{"key":"大米星球","name":"🌎大米星球(量)🍭♒","type":3,"api":"./lib/drpy2.min.js","ext":"./js/大米星球.js"},
{"key":"Nofit_酷6网.js","name":"酷6网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷6网.js"},
{"key":"Nofit_网易公版影像.js","name":"网易公版影像.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/网易公版影像.js"},
{"key":"Nofit_爱看影院.js","name":"爱看影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱看影院.js"},
{"key":"Nofit_博看听书.js","name":"博看听书.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/博看听书.js"},
{"key":"Nofit_六月听书.js","name":"六月听书.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/六月听书.js"},
{"key":"Nofit_alistjar.json","name":"alistjar.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/alistjar.json"},
{"key":"Nofit_A8音乐.js","name":"A8音乐.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/A8音乐.js"},
{"key":"Nofit_幻听网听书.js","name":"幻听网听书.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/幻听网听书.js"},
{"key":"Nofit_喜马拉雅.js","name":"喜马拉雅.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/喜马拉雅.js"},
{"key":"Nofit_厂长资源.js","name":"厂长资源.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/厂长资源.js"},
{"key":"Nofit_追剧迷.js","name":"追剧迷.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧迷.js"},
{"key":"Nofit_爱弹幕.js","name":"爱弹幕.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱弹幕.js"},
{"key":"Nofit_360影视.js","name":"360影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/360影视.js"},
{"key":"Nofit_音悦网.js","name":"音悦网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/音悦网.js"},
{"key":"Nofit_种子音乐.js","name":"种子音乐.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/种子音乐.js"},
{"key":"Nofit_短视频.js","name":"短视频.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/短视频.js"},
{"key":"Nofit_海洋听书.js","name":"海洋听书.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海洋听书.js"},
{"key":"Nofit_时光影视.js","name":"时光影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/时光影视.js"},
{"key":"Nofit_kunyu77.js","name":"kunyu77.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/kunyu77.js"},
{"key":"Nofit_ddys.js","name":"ddys.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/ddys.js"},
{"key":"Nofit_GAOAA.json","name":"GAOAA.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/GAOAA.json"},
{"key":"Nofit_香蕉AV解说.json","name":"香蕉AV解说.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉AV解说.json"},
{"key":"Nofit_猫了个咪.js","name":"猫了个咪.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/猫了个咪.js"},
{"key":"Nofit_HD.js","name":"HD.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HD.js"},
{"key":"Nofit_18av.js","name":"18av.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/18av.js"},
{"key":"Nofit_banan.js","name":"banan.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/banan.js"},
{"key":"Nofit_Missav.js","name":"Missav.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/Missav.js"},
{"key":"Nofit_养端.js","name":"养端.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/养端.js"},
{"key":"Nofit_吸瓜.js","name":"吸瓜.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/吸瓜.js"},
{"key":"Nofit_朱古力.js","name":"朱古力.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/朱古力.js"},
{"key":"Nofit_玩偶姐姐.js","name":"玩偶姐姐.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/玩偶姐姐.js"},
{"key":"Nofit_香蕉超清资源.json","name":"香蕉超清资源.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉超清资源.json"},
{"key":"Nofit_香蕉资源搜索.json","name":"香蕉资源搜索.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉资源搜索.json"},
{"key":"Nofit_香蕉资源.json","name":"香蕉资源.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉资源.json"},
{"key":"Nofit_香蕉视频.json","name":"香蕉视频.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉视频.json"},
{"key":"Nofit_精东影业1.json","name":"精东影业1.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/精东影业1.json"},
{"key":"Nofit_香蕉直播.json","name":"香蕉直播.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉直播.json"},
{"key":"Nofit_香蕉废柴网.json","name":"香蕉废柴网.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉废柴网.json"},
{"key":"Nofit_香蕉久久热.json","name":"香蕉久久热.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉久久热.json"},
{"key":"Nofit_香蕉国产传媒.json","name":"香蕉国产传媒.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/香蕉国产传媒.json"},
{"key":"Nofit_床吧搜索.json","name":"床吧搜索.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/床吧搜索.json"},
{"key":"Nofit_床吧.json","name":"床吧.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/床吧.json"},
{"key":"Nofit_叫床吧.json","name":"叫床吧.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/叫床吧.json"},
{"key":"Nofit_麻豆女优.json","name":"麻豆女优.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/麻豆女优.json"},
{"key":"Nofit_黄瓜TV.json","name":"黄瓜TV.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/黄瓜TV.json"},
{"key":"Nofit_18AV.json","name":"18AV.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/18AV.json"},
{"key":"Nofit_banan.json","name":"banan.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/banan.json"},
{"key":"Nofit_精东影业.json","name":"精东影业.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/精东影业.json"},
{"key":"Nofit_麻豆映画.json","name":"麻豆映画.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/麻豆映画.json"},
{"key":"Nofit_AVideo.json","name":"AVideo.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/AVideo.json"},
{"key":"Nofit_23999.json","name":"23999.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/23999.json"},
{"key":"Nofit_性欲轮回.json","name":"性欲轮回.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/性欲轮回.json"},
{"key":"Nofit_UrleBird.js","name":"UrleBird.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/UrleBird.js"},
{"key":"Nofit_麦豆.js","name":"麦豆.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/麦豆.js"},
{"key":"Nofit_饭团.js","name":"饭团.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/饭团.js"},
{"key":"Nofit_新安影院.js","name":"新安影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新安影院.js"},
{"key":"Nofit_l0l.js","name":"l0l.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/l0l.js"},
{"key":"Nofit_JRKAN直播.js","name":"JRKAN直播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/JRKAN直播.js"},
{"key":"Nofit_麻花影视.js","name":"麻花影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/麻花影视.js"},
{"key":"Nofit_麦豆com.js","name":"麦豆com.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/麦豆com.js"},
{"key":"Nofit_骚火电影.js","name":"骚火电影.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/骚火电影.js"},
{"key":"Nofit_音乐演唱.json","name":"音乐演唱.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/音乐演唱.json"},
{"key":"Nofit_霹雳影视.js","name":"霹雳影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/霹雳影视.js"},
{"key":"Nofit_零柒影视.js","name":"零柒影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/零柒影视.js"},
{"key":"Nofit_雅克坊.js","name":"雅克坊.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/雅克坊.js"},
{"key":"Nofit_闪影影院.js","name":"闪影影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/闪影影院.js"},
{"key":"Nofit_酷酷韩剧.js","name":"酷酷韩剧.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷酷韩剧.js"},
{"key":"Nofit_酷奇MV.js","name":"酷奇MV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/酷奇MV.js"},
{"key":"Nofit_追剧影视.js","name":"追剧影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧影视.js"},
{"key":"Nofit_追剧喵.js","name":"追剧喵.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧喵.js"},
{"key":"Nofit_追剧啦.js","name":"追剧啦.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/追剧啦.js"},
{"key":"Nofit_趣享星趣.js","name":"趣享星趣.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/趣享星趣.js"},
{"key":"Nofit_超前点播.js","name":"超前点播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/超前点播.js"},
{"key":"Nofit_视觉影院.js","name":"视觉影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/视觉影院.js"},
{"key":"Nofit_视中心影视.js","name":"视中心影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/视中心影视.js"},
{"key":"Nofit_西瓜影视.js","name":"西瓜影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/西瓜影视.js"},
{"key":"Nofit_蜻蜓FM.js","name":"蜻蜓FM.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蜻蜓FM.js"},
{"key":"Nofit_蛋蛋魔法.js","name":"蛋蛋魔法.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蛋蛋魔法.js"},
{"key":"Nofit_蛋蛋赞.js","name":"蛋蛋赞.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蛋蛋赞.js"},
{"key":"Nofit_蚂蚁影视.js","name":"蚂蚁影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/蚂蚁影视.js"},
{"key":"Nofit_艾菲影视.js","name":"艾菲影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/艾菲影视.js"},
{"key":"Nofit_艾旦影视.js","name":"艾旦影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/艾旦影视.js"},
{"key":"Nofit_艾斯影院.js","name":"艾斯影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/艾斯影院.js"},
{"key":"Nofit_胖虎影视.js","name":"胖虎影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/胖虎影视.js"},
{"key":"Nofit_米宝影院.js","name":"米宝影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/米宝影院.js"},
{"key":"Nofit_秋霞.js","name":"秋霞.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/秋霞.js"},
{"key":"Nofit_碟调影视.js","name":"碟调影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/碟调影视.js"},
{"key":"Nofit_看视界.js","name":"看视界.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看视界.js"},
{"key":"Nofit_看片狂人.js","name":"看片狂人.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看片狂人.js"},
{"key":"Nofit_看BZ影视.js","name":"看BZ影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/看BZ影视.js"},
{"key":"Nofit_皮皮泡.js","name":"皮皮泡.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/皮皮泡.js"},
{"key":"Nofit_电影大师.js","name":"电影大师.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/电影大师.js"},
{"key":"Nofit_瓜皮TV.js","name":"瓜皮TV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/瓜皮TV.js"},
{"key":"Nofit_玄天.js","name":"玄天.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/玄天.js"},
{"key":"Nofit_猫影汇.js","name":"猫影汇.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/猫影汇.js"},
{"key":"Nofit_特狗影视.js","name":"特狗影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/特狗影视.js"},
{"key":"Nofit_牛马TV.js","name":"牛马TV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/牛马TV.js"},
{"key":"Nofit_爱车MV.js","name":"爱车MV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱车MV.js"},
{"key":"Nofit_爱看电影.js","name":"爱看电影.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱看电影.js"},
{"key":"Nofit_爱看影视.js","name":"爱看影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱看影视.js"},
{"key":"Nofit_爱猫影院.js","name":"爱猫影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/爱猫影院.js"},
{"key":"Nofit_煲剧吧.js","name":"煲剧吧.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/煲剧吧.js"},
{"key":"Nofit_海盗听书.js","name":"海盗听书.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/海盗听书.js"},
{"key":"Nofit_欧乐影院.js","name":"欧乐影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/欧乐影院.js"},
{"key":"Nofit_枫林网.js","name":"枫林网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/枫林网.js"},
{"key":"Nofit_有声小说吧.js","name":"有声小说吧.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/有声小说吧.js"},
{"key":"Nofit_新思古影院.js","name":"新思古影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/新思古影院.js"},
{"key":"Nofit_斗鱼直播.js","name":"斗鱼直播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/斗鱼直播.js"},
{"key":"Nofit_捷华影视.js","name":"捷华影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/捷华影视.js"},
{"key":"Nofit_抓饭体育.js","name":"抓饭体育.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/抓饭体育.js"},
{"key":"Nofit_我爱电影网.js","name":"我爱电影网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/我爱电影网.js"},
{"key":"Nofit_思乐影视.js","name":"思乐影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/思乐影视.js"},
{"key":"Nofit_快云影院.js","name":"快云影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/快云影院.js"},
{"key":"Nofit_影视工厂.js","name":"影视工厂.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/影视工厂.js"},
{"key":"Nofit_库马伊.js","name":"库马伊.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/库马伊.js"},
{"key":"Nofit_小白菜电影.js","name":"小白菜电影.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小白菜电影.js"},
{"key":"Nofit_小强迷.js","name":"小强迷.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小强迷.js"},
{"key":"Nofit_小品网.js","name":"小品网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/小品网.js"},
{"key":"Nofit_完美看看.js","name":"完美看看.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/完美看看.js"},
{"key":"Nofit_宅腐影视.js","name":"宅腐影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/宅腐影视.js"},
{"key":"Nofit_好多影视.js","name":"好多影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/好多影视.js"},
{"key":"Nofit_天天影视.js","name":"天天影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/天天影视.js"},
{"key":"Nofit_城市影视.js","name":"城市影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/城市影视.js"},
{"key":"Nofit_在线之家Ⅱ.js","name":"在线之家Ⅱ.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/在线之家Ⅱ.js"},
{"key":"Nofit_在线189.js","name":"在线189.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/在线189.js"},
{"key":"Nofit_唐人街影视.js","name":"唐人街影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/唐人街影视.js"},
{"key":"Nofit_听书网.js","name":"听书网.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/听书网.js"},
{"key":"Nofit_南瓜影院.js","name":"南瓜影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/南瓜影院.js"},
{"key":"Nofit_剧荒TV.js","name":"剧荒TV.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧荒TV.js"},
{"key":"Nofit_剧荒.js","name":"剧荒.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/剧荒.js"},
{"key":"Nofit_凌云.js","name":"凌云.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/凌云.js"},
{"key":"Nofit_兰花影院.js","name":"兰花影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/兰花影院.js"},
{"key":"Nofit_兔小贝.js","name":"兔小贝.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/兔小贝.js"},
{"key":"Nofit_人人影视.js","name":"人人影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/人人影视.js"},
{"key":"Nofit_云播.js","name":"云播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/云播.js"},
{"key":"Nofit_乐动影视.js","name":"乐动影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/乐动影视.js"},
{"key":"Nofit_七小时影院.js","name":"七小时影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/七小时影院.js"},
{"key":"Nofit_YOKE影视.js","name":"YOKE影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/YOKE影视.js"},
{"key":"Nofit_vidhub.js","name":"vidhub.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/vidhub.js"},
{"key":"Nofit_TV蜂.js","name":"TV蜂.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/TV蜂.js"},
{"key":"Nofit_TV云播.js","name":"TV云播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/TV云播.js"},
{"key":"Nofit_TF影院.js","name":"TF影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/TF影院.js"},
{"key":"Nofit_KOK影视.js","name":"KOK影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KOK影视.js"},
{"key":"Nofit_HoHo影视.js","name":"HoHo影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HoHo影视.js"},
{"key":"Nofit_HDmoli.js","name":"HDmoli.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/HDmoli.js"},
{"key":"Nofit_DJ音乐.js","name":"DJ音乐.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/DJ音乐.js"},
{"key":"Nofit_BD影视.js","name":"BD影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/BD影视.js"},
{"key":"Nofit_BD360.js","name":"BD360.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/BD360.js"},
{"key":"Nofit_alist.json","name":"alist.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/alist.json"},
{"key":"Nofit_99影院.js","name":"99影院.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/99影院.js"},
{"key":"Nofit_88看球.js","name":"88看球.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/88看球.js"},
{"key":"Nofit_310直播.js","name":"310直播.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/310直播.js"},
{"key":"Nofit_2099电影.js","name":"2099电影.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/2099电影.js"},
{"key":"Nofit_ck资源.js","name":"ck资源.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/ck资源.js"},
{"key":"Nofit_KUBO影视.js","name":"KUBO影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/KUBO影视.js"},
{"key":"Nofit_lives.txt","name":"lives.txt","type":3,"api":"./lib/drpy2.min.js","ext":"./js/lives.txt"},
{"key":"Nofit_if101.js","name":"if101.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/if101.js"},
{"key":"Nofit_util.ym.js","name":"util.ym.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/util.ym.js"},
{"key":"Nofit_TVB影视.js","name":"TVB影视.js","type":3,"api":"./lib/drpy2.min.js","ext":"./js/TVB影视.js"},
{"key":"Nofit_解析.conf","name":"解析.conf","type":3,"api":"./lib/drpy2.min.js","ext":"./js/解析.conf"},
{"key":"Nofit_rules.py","name":"rules.py","type":3,"api":"./lib/drpy2.min.js","ext":"./js/rules.py"},
{"key":"Nofit_alist.conf","name":"alist.conf","type":3,"api":"./lib/drpy2.min.js","ext":"./js/alist.conf"},
{"key":"Nofit_py.json","name":"py.json","type":3,"api":"./lib/drpy2.min.js","ext":"./js/py.json"},
{"key":"Nofit_直播.txt","name":"直播.txt","type":3,"api":"./lib/drpy2.min.js","ext":"./js/直播.txt"},
{"key":"filter_粤爱看","name":"🇭🇰粤爱看🔎","type":3,"api":"./lib/drpy2.min.js","ext":"./js/粤爱看.js"}
],
"lives": [
    {
      "name": "直播源",
      "type": 0,
      "url": "./直播源.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },    
    {
      "name": "FongMi",
      "type": 1,
      "url": "https://raw.githubusercontent.com/FongMi/CatVodSpider/main/json/live.json",
      "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={epg}&date={date}",
      "logo": "http://epg.51zmt.top:8000/{logo}"
    },
    {
      "name": "台灣",
      "type": 0,
      "url": "./live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
        {
      "name": "直播1",
      "type": 0,
      "url": "http://home.jundie.top:81/Cat/tv/live.txt",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    },
    {
      "name": "直播2",
      "type": 0,
      "url": "https://dashu0754.com/api/v3/file/get/111/%E6%82%9F%E7%A9%BA.txt?sign=Vh_6WlBWzq1GeV88r1QjRQE9DCNcz5rBZpmSMo_q_y8%3D%3A0",
      "epg": "https://epg.112114.xyz/?ch={name}&date={date}",
      "logo": "https://epg.112114.xyz/logo/{name}.png"
    }
  ],
"rules":[
{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
{"host":"hdmoli.com","rule":[".m3u8"]},{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]}],
"parses":[
{"name":"懒懒","type":1,"url":"http://lanlan.ckflv.cn/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"猫爪","type":0,"url":"https://jx.zhanlangbu.com/?url="},
{"name":"ok","type":0,"url":"https://okjx.cc/?url="},
{"name":"bozrc","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":""}}},
{"name":"不累","type":0,"url":"https://blbfq.f3322.net/player/analysis.php?v=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"cod","type":0,"url":"https://ksksl.codjx.com/?url="},
{"name":"byg解析","type":0,"url":"https://byg.ziqj5.shop/?url="},
{"name":"xmflv","type":0,"url":"https://jx.xmflv.com/?url="},
{"name":"365","type":0,"url":"https://chaxun.truechat365.com/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"26db","type":0,"url":"http://vip.26db.cn/g/?url="},
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"FreeOK","type":0,"url":"https://play.86516.tk/OKPlayer/?url="},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url="}],
"ads": ["https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-i-dy/455ccf9e8ae744378118e4bd289288dd","mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg"
}