{
"sites" : [
{"key":"drpy","name":"豆瓣🍭🔎(简体)","type":3,"api":"drpy2.min.js","ext":"./js/豆瓣.js"},
{"key":"drpy2","name":"豆瓣2🍭🔎","type":3,"api":"drpy2.min.js","ext":"./js/drpy.js"},
{"key":"drpy__豆瓣","name":"豆瓣🏛[DRPY]🔎","type":3,"api":"drpy2.min.js","ext":"https://raw.githubusercontent.com/hjdhnx/dr_py/main/js/drpy.js"},
{"key":"ikanbotsq","name":"🈵爱看机器人sq(简体)","type":3,"api":"drpy2.min.js","ext":"./js/ikanbotsq.js"},
{"key":"drpy_js_360影视","name":"官源🏛360","type":3,"api":"drpy2.min.js","ext":"./js/360影视.js"},
{"key":"drpy_js_百忙无果","name":"官源🏛芒果🔎","type":3,"api":"drpy2.min.js","ext":"./js/百忙无果.js"},
{"key":"drpy_js_奇珍异兽","name":"官源🏛爱奇艺🍭🔎","type":3,"api":"drpy2.min.js","ext":"./js/奇珍异兽.js"},
{"key":"drpy_js_腾云驾雾","name":"官源🏛腾讯🔎","type":3,"api":"drpy2.min.js","ext":"./js/腾云驾雾.js"},
{"key":"drpy_js_优酷","name":"官源🏛优酷🔎","type":3,"api":"drpy2.min.js","ext":"./js/优酷.js"},
{"key":"欧乐影院","name":"🛩歐樂影院♒(简体)","type":3,"api":"drpy2.min.js","ext":"./js/欧乐影院.js"},
{"key":"独播库","name":"🛩独播库🔎(简体)","type":3,"api":"drpy2.min.js","ext":"./js/独播库[飞].js","playerType":"1"},
{"key":"欧帝影院","name":"🛩欧帝影院🔎(简体)","type":3,"api":"drpy2.min.js","ext":"./js/欧帝影院.js"},
{"key":"泥巴","name":"🏆泥巴🔎(简体)","type":3,"api":"csp_Nbys","searchable":1,"filterable":1,"jar":"./top98_1.jar"},
{"key": "星星","name": "🏆星星(简体)","type": 3,"api": "csp_Star","searchable": 1,"jar":"./FongMi_custom_spider.jar"},
{"key":"快看资源网","name":"🏆快看资源(简体)","type":0,"api":"https://kuaikan-api.com/api.php/provide/vod/at/xmlsea","searchable":1,"quickSearch":1,"filterable":1},
{"key":"優質资源网","name":"🏆優質资源1080(简体)","type":0,"api":"https://api.1080zyku.com/inc/api.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"暴风影视","name":"🏆暴风影视(简体)","type":1,"api":"https://bfzyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"大漠影视e","name":"🏆大漠影视(简体)","type":1,"api":"https://damozy.com/api.php/provide/vod/from/M3U8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"索尼","name":"🏆索尼(简体)","type":1,"api":"https://suoniapi.com/api.php/provide/vod","searchable":1,"quickSearch":1,"filterable":1},
{"key":"索尼2","name":"🏆索尼2(简体)","type":0,"api":" https://suoniapi.com/api.php/provide/vod/from/snm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"豪华资源","name":"🏆豪华资源(简体)","type":0,"api":"https://hhzyapi.com/api.php/provide/vod/from/hhm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key": "种子","name": "🏆种子短剧资源","type": 1,"api": "http://zzdj.cc/api.php/provide/vod/","searchable": 1,"quickSearch": 1,"filterable": 1},
{"key":"taopian資源f","name":"🏆taopian資源(淘片)(简体)","type":1,"api":"https://taopianapi.com/cjapi/mc/vod/json/m3u8.html","searchable":1,"quickSearch":1,"filterable":1},
{"key":"淘片资源网","name":"🏆淘片资源tp(简体)","type":0,"api":"https://taopianapi.com/home/cjapi/as/mc/vod/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"非凡资源网","name":"🏆非凡资源ff(简体)","type":0,"api":"http://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"量子资源網","name":"🏆量子资源lz(简体)","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1,"categories":["国产剧","国产动漫","泰国剧","台湾剧","香港剧","欧美剧","韩国剧","日本剧","动漫","体育","剧情片","动作片","爱情片","喜剧片"]},
{"key":"ikun资源网","name":"🏆ikun资源(简体)","type":0,"api":"https://ikunzyapi.com/api.php/provide/vod/from/ikm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"oletv資源f","name":"🏆oletv資源(海外)(简体)","type":1,"api":"https://olevod1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
//{"key":"快帆","name":"快帆(简体)","type":1,"api":"https://api.kuaifan.tv/api.php/provide/vod","searchable":1,"quickSearch":1,"filterable":1},
{"key":"多瑙影视","name":"🈵多瑙影视♒","type":3,"api":"drpy2.min.js","ext":"./js/多瑙影视.js"},
{"key":"厂长资源","name":"🎯厂长资源(简体)","type":3,"api":"drpy2.min.js","ext":"./js/厂长资源.js"},
{"key":"电影先生","name":"🎯电影先生(简体)","type":3,"api":"drpy2.min.js","ext":"./js/电影先生.js"},
{"key":"南瓜影视","name":"🎯南瓜影视(简体)","type":3,"api":"drpy2.min.js","ext":"./js/南瓜影视.js"},
{"key":"极速影视e","name":"🏆极速影视(简体)","type":1,"api":"https://jszyapi.com/api.php/provide/vod/from/jsm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"天空资源网","name":"🏆天空资源网tk(简体)","type":0,"api":"https://api.tiankongapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"飞速资源","name":"🏆飞速资源(简体)","api":"https://www.feisuzy.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"海外看资源网","name":"🏆海外看haiwaikan(简体)","type":0,"api":"https://haiwaikan.com/api.php/provide/vod/at/xml/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鹰影视e","name":"🏆金鹰影视(简体)","type":1,"api":"https://jinyingzy.com/provide/vod/from/jinyingm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"77韩剧","name":"🏆77韩剧(简体)","api":"https://www.77hanju.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"韩剧资源","name":"🏆韩剧资源(简体)","api":"http://www.hanjuzy.com/inc/apijson_vod.php","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"shoujihanju資源f","name":"🌟shoujihanju(韓劇)(简体)","type":1,"api":"https://77hanju.com/api.php/provide/vod/from/mkm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"U酷资源網","name":"🏆U酷资源(简体)","type":1,"api":"https://api.ukuapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"奇虎影视e","name":"🌟奇虎影视(简体)","type":1,"api":"https://caiji.qhzyapi.com/api.php/provide/vod/from/qhm3u8/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"飛速资源网","name":"🌟飛速资源fe(简体)","type":0,"api":"https://www.feisuzyapi.com/api.php/provide/vod/from/fsm3u8/at/xml","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快播资源網","name":"🌟快播资源kb(简体)","type":1,"api":"http://www.kuaibozy.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"快车资源網","name":"🌟快车资源kc(简体)","type":1,"api":"https://caiji.kczyapi.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"樱花资源網","name":"🌟樱花资源yh(简体)","type":1,"api":"https://m3u8.apiyhzy.com/api.php/provide/vod/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"68资源网","name":"🌟68资源68(简体)","type":0,"api":"https://caiji.68zyapi.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"if101","name":"🌟if101(简体)","type":3,"api":"drpy2.min.js","ext":"./js/if101.js"},
{"key":"CK资源采集网","name":"🏆CK资源采集网(简体)","type":1,"api":"https://ckzy.me/api.php/provide/vod/?ac=list","searchable":1,"quickSearch":1,"filterable":1},
{"key":"CK资源(VPN)","name":"🛩CK资源(VPN)(简体)","type":3,"api":"drpy2.min.js","ext":"./js/ck资源.js"},
{"key":"八戒资源网","name":"🏆八戒资源网(简体)","type":1,"api":"http://cj.bajiecaiji.com/inc/apijson_vod.php","searchable":1,"quickSearch":1,"filterable":1},
{"key":"易看资源","name":"🌕易看资源♒yikan","api":"https://api.yikanapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"卧龙资源網","name":"🌕卧龙资源wolong","type":1,"api":"https://collect.wolongzyw.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"新浪资源","name":"🌕新浪资源xl","type":0,"api":"https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"鱼乐资源網","name":"🌕鱼乐资源le","type":1,"api":"https://api.ylzy1.com/api.php/provide/vod/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鷹资源网","name":"🌕金鷹资源jyz","type":0,"api":"https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"红牛资源","name":"🌕红牛资源hn","type":0,"api":"https://www.hongniuzy2.com/api.php/provide/vod/at/xml/","searchable":1,"quickSearch":1,"filterable":1},
{"key":"ikanbot2","name":"爱看机器人2","type":3,"api":"drpy2.min.js","ext":"./js/ikanbot2.js"},
{"key":"ikanbot3","name":"爱看机器人3","type":3,"api":"drpy2.min.js","ext":"./js/ikanbot3.js"}
],
"lives":[{"name":"自選","type":0,"url":"./live.txt","epg":"https://epg.112114.xyz/?ch={name}&date={date}","logo":"https://epg.112114.xyz/logo/{name}.png"}],
"doh":[{"name":"Google","url":"https://dns.google/dns-query","ips":["8.8.4.4","8.8.8.8"]},{"name":"Cloudflare","url":"https://cloudflare-dns.com/dns-query","ips":["1.1.1.1","1.0.0.1","2606:4700:4700::1111","2606:4700:4700::1001"]},{"name":"AdGuard","url":"https://dns.adguard.com/dns-query","ips":["94.140.14.140","94.140.14.141"]},{"name":"DNSWatch","url":"https://resolver2.dns.watch/dns-query","ips":["84.200.69.80","84.200.70.40"]},{"name":"Quad9","url":"https://dns.quad9.net/dns-quer","ips":["9.9.9.9","149.112.112.112"]}],
"rules":[{"name":"proxy","hosts":["raw.githubusercontent.com","googlevideo.com","cdn.v82u1l.com","cdn.iz8qkg.com","cdn.kin6c1.com","c.biggggg.com","c.olddddd.com","haiwaikan.com","www.histar.tv","youtube.com","uhibo.com",".*boku.*",".*nivod.*",".*ulivetv.*"]},{"name":"海外看","hosts":["haiwaikan"],"regex":["10.0099","10.3333","16.0599","8.1748","10.85"]},{"name":"索尼","hosts":["suonizy"],"regex":["15.1666","15.2666"]},{"name":"暴風","hosts":["bfzy"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:3,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},{"name":"星星","hosts":["aws.ulivetv.net"],"regex":["#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:8,[\\s\\S]*?#EXT-X-DISCONTINUITY"]},{"name":"量子","hosts":["vip.lz","hd.lz","v.cdnlz"],"regex":["18.5333"]},{"name":"非凡","hosts":["vip.ffzy","hd.ffzy"],"regex":["25.0666"]},{"name":"火山嗅探","hosts":["huoshan.com"],"regex":["item_id="]},{"name":"抖音嗅探","hosts":["douyin.com"],"regex":["is_play_url="]},{"name":"農民嗅探","hosts":["toutiaovod.com"],"regex":["video/tos/cn"]}],
"parses":[
{"name":"777","type":0,"url":"https://jx.777jiexi.com/player/?url="},
{"name":"杰森","type":0,"url":"https://jx.jsonplayer.com/player/?url="}, 
{"name":"看看","type":0,"url":"https://jx.m3u8.pw/?url="},
{"name":"A01","type":0,"url":"http://api.apii.top/?v="},
{"name":"A05","type":0,"url":"http://www.wpsseo.cn/line.php?n=7&url="},
{"name":"A12","type":0,"url":"https://jx.quankan.app/?url="},
{"name":"A14","type":0,"url":"https://www.pangujiexi.com/pangu/?url="},
{"name":"9号线","url":"https://www.8090g.cn/?url="},
{"name":"12号线","type":0,"url":"https://jx.m3u8.tv/jiexi/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"17号线","type":0,"url":"https://www.yemu.xyz/?url=","ext":{"flag":["qq","腾讯","qiyi","iqiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"👉嗅探👈就是破解中，請等候一會👈","type":0,"url":"http://pandown.pro/app/ysmjx.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}}],
"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu"],
"wallpaper":"./黑色.jpeg",
"ads":["mozai.4gtv.tv"]

}