{
  "sites": [
{"key":"U酷资源","name":"U酷资源","api":"https://api.ukuapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"77韩剧","name":"77韩剧","api":"https://www.77hanju.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"1080资源库","name":"1080资源库","api":"https://api.1080zyku.com/inc/api_mac10.php","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"ckzy","name":"CK资源","api":"https://ckzy.me/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"U酷资源","name":"U酷资源","api":"https://api.ukuapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"vipmv","name":"天堂资源","api":"http://vipmv.cc/api.php/provide/vod","type":1,"jiexiUrl":"https://titan.mgtv.com.o8tv.com/jiexi/?url="},
{"key":"zzrhgg","name":"飘花资源","api":"http://www.zzrhgg.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"阿里影视","name":"阿里影视","api":"http://aliys.cn:90/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"八戒资源","name":"八戒资源","api":"http://cj.bajiecaiji.com/inc/apijson_vod.php","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"百度资源","name":"百度资源","api":"https://api.apibdzy.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"飞速资源","name":"飞速资源","api":"https://www.feisuzy.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"光速资源","name":"光速资源","api":"https://api.guangsuapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"韩剧资源","name":"韩剧资源","api":"http://www.hanjuzy.com/inc/apijson_vod.php","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"红牛资源","name":"红牛资源","api":"https://www.hongniuzy2.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鹰资源","name":"金鹰资源","api":"http://jinyingzy.com/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"考拉TV","name":"考拉TV","api":"https://ikaola.tv/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"快播资源2","name":"快播资源2","api":"http://www.kuaibozy.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"快车资源","name":"快车资源","api":"https://caiji.kczyapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"乐活影视","name":"乐活影视","api":"https://lehootv.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"量子资源","name":"量子资源","api":"http://cj.lziapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"诺讯资源","name":"诺讯资源","api":"https://caiji.nxflv.com/api.php/provide/vod/","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"飘花电影","name":"飘花电影","api":"http://www.zzrhgg.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"闪电资源","name":"闪电资源","api":"http://sdzyapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"瞬间影视","name":"瞬间影视","api":"http://app.7en7.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"天空资源","name":"天空资源","api":"https://api.tiankongapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"天空资源2","name":"天空资源2","api":"https://api.tiankongapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"卧龙资源","name":"卧龙资源","api":"https://collect.wolongzyw.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"新浪资源","name":"新浪资源","api":"http://api.xinlangapi.com/xinlangapi.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"忆梦资源","name":"忆梦资源","api":"http://anltv.cn/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"易看资源","name":"易看资源♒","api":"https://api.yikanapi.com/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"映迷","name":"映迷","api":"https://www.inmi.app/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"雨哥影视","name":"雨哥影视","api":"http://cj.baozi66.top:66/api.php/provide/vod","type":1,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"6Uzy0","name":"6U资源0","api":"http:zy.ataoju.com/inc/api.php","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"39影视0","name":"39影视0","api":"https:www.39kan.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"51看剧0","name":"51看剧0","api":"http:www.51kanju.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"FOX资源0","name":"FOX资源0","api":"https:api.foxzyapi.com/api.","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"kudian80","name":"酷点资源20","api":"https:kudian8.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"leduozy0","name":"乐多资源网0","api":"http:api.leduozy.com/inc/api.php","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"MX影院0","name":"MX影院0","api":"http:49.235.107.145:81/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"OmoFun0","name":"OmoFun0","api":"https:app.omofun.net/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"taopianapi0","name":"淘片资源采集网0","api":"https:taopianapi.com/home/cjapi/as/mc/vod/xml","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"travelbooking0","name":"唯一资源0","api":"http:api.travelbooking.cc/xml","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"TOM资源0","name":"TOM资源0","api":"https:api.tomcaiji.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"XYUI0","name":"XYUI0","api":"http:jx4.xyui.top:7001/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"yilans0","name":"8090资源0","api":"http:zy.yilans.net:8090/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"yparse0","name":"步步高资源0","api":"https:api.yparse.com/api/xml","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"yulecj0","name":"鱼乐资源网0","api":"https:api.yulecj.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"zycaiji0","name":"星辰资源0","api":"http:www.zycaiji.net:7788/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"爱兜视频0","name":"爱兜视频0","api":"http:id190.tpddns.cn:81/mogai_api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"爱酷影视0","name":"爱酷影视0","api":"https:www.zhanlangbu.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"艾思影院0","name":"艾思影院0","api":"https:www.aitee.cc/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"百淘影视0","name":"百淘影视0","api":"http:ys.58g8.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"北川影视0","name":"北川影视0","api":"https:www.bcwzg.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"波比影视0","name":"波比影视0","api":"http:xxhhsc.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"波比影视0","name":"波比影视0","api":"http:xxhhsc.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"创艺影视0","name":"创艺影视0","api":"https:www.30dian.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"段友影视0","name":"段友影视0","api":"http:shangjihuoke.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"多多资源0","name":"多多资源0","api":"https:www.ddzyz1.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"多多资源20","name":"多多资源20","api":"https:a.7dyu.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"番茄资源0","name":"番茄资源0","api":"http:api.fqzy.cc/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"冠军资源0","name":"冠军资源0","api":"https:www.cmpzy.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"海外电影0","name":"海外电影0","api":"https:www.200121.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"海玉影视0","name":"海玉影视0","api":"http:tv2.hykjtv.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"幻风影视0","name":"幻风影视0","api":"http:vip857.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"江湖官采0","name":"江湖官采0","api":"http:119.29.1.173/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"金鹰资源20","name":"金鹰资源20","api":"https:jyzyapi.com/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"橘猫影视0","name":"橘猫影视0","api":"http:www.zitv.cc/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"看看资源0","name":"看看资源0","api":"https:zy.hikan.xyz/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"考拉TV20","name":"考拉TV20","api":"https:ikaola.tv/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"酷点资源0","name":"酷点资源0","api":"https:kudianzy.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"快播资源0","name":"快播资源0","api":"http:www.kuaibozy.com/api.php/provide/vod/from/kbm3u8","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"乐活影视0","name":"乐活影视0","api":"https:lehootv.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"每天看看0","name":"每天看看0","api":"http:47.113.126.237:1234/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"铭轩影视0","name":"铭轩影视0","api":"http:lz0716.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"木子看剧0","name":"木子看剧0","api":"https:mzkj.maccms.cf/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"南国影源0","name":"南国影源0","api":"http:api.nguonphim.tv/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"诺讯资源0","name":"诺讯资源0","api":"http:caiji.nxflv.com/api.php/provide/vod","type":0,"jiexiUrl":"https:www.nxflv.com/?url="},
{"key":"盘看看0","name":"盘看看0","api":"http:tvcaiji.pankk.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"蒲公英视频0","name":"蒲公英视频0","api":"http:www.pgy1.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"奇粹影视0","name":"奇粹影视0","api":"http:www.blssv.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"千寻时光0","name":"千寻时光0","api":"http:wy.dqyhg.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"神速资源0","name":"神速资源0","api":"https:api.sszyapi.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"思古影院0","name":"思古影院0","api":"https:www.siguyy.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"速更资源0","name":"速更资源0","api":"https:sugengzy.cn/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"速影0","name":"速影0","api":"https:速影128.xyz/inc/apijson.php","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"天天影视0","name":"天天影视0","api":"http:tt2022.ga/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"土剧TV0","name":"土剧TV0","api":"http:tujutv.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"网民电影0","name":"网民电影0","api":"https:www.prinevillesda.org/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"蜗牛动漫0","name":"蜗牛动漫0","api":"http:woniudm.woniu.cyou:20000/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"西柚影视0","name":"西柚影视0","api":"http:43.135.75.180:9999/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"香瓜影视0","name":"香瓜影视0","api":"http:v.xgvod.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"想看资源0","name":"想看资源0","api":"https:m3u8.xiangkanapi.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"小猫咪0","name":"小猫咪0","api":"http:zy.xiaomaomi.cc/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"小鸟动漫0","name":"小鸟动漫0","api":"http:xydm.baicai.buzz/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"益达影院0","name":"益达影院0","api":"http:luobu.yss6080.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"樱花资源0","name":"樱花资源0","api":"https:m3u8.apiyhzy.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"影图资源0","name":"影图资源0","api":"https:cj.vodimg.top/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"鱼乐资源0","name":"鱼乐资源0","api":"https:api.ylzy1.com/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key":"醉璃笙TV0","name":"醉璃笙TV0","api":"http:web.xhdj.vip/api.php/provide/vod","type":0,"searchable":1,"quickSearch":1,"filterable":1},
{"key": "MBO 影视0", "name": "MBO 影视0","api": "https://www.mbomovie.com/api.php/provide/vod/","type": 0,"jiexiUrl": "","group": "影视","isActive": true,"status": "true"}
    ],
 
  "iptv": [
      {
        "id": 1,
        "name": "饭太硬直播",
        "url": "http://ftyyy.tk/live.txt",
        "playerType": 1,
        "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={name}&date={date}",
        "isActive": true 
      },
      {
        "id": 2,
        "name": "FongMi直播",
        "type": 0,
        "url": "http://home.jundie.top:81/Cat/tv/live.txt",
        "epg": "http://epg.51zmt.top:8000/api/diyp/?ch={name}&date={date}",
        "isActive": true 
      }
    ],
  
  "analyzes": [
      {"name":"解析1","url":"https://jx.777jiexi.com/player/?url=","isActive": true}, 
      {"name":"解析2","url":"https://jx.bozrc.com:4433/player/?url=","isActive": true}, 
      {"name":"解析3","url":"https://www.ckmov.vip/api.php?url=","isActive": true},
      {"name":"解析4","url":"https://www.h8jx.com/jiexi.php?url=","isActive": true},
      {"name":"解析5","url":"https://jx.playerjy.com/?url=","isActive": true},
      {"name":"解析6","url":"https://www.playm3u8.cn/jiexi.php?url=","isActive": true},
      {"name":"解析7","url":"https://api.jiexi.la/?url=","isActive": true},
      {"name":"解析8","url":"https://jx.ivito.cn/?url=","isActive": true},
      {"name":"解析9","url":"https://www.8090g.cn/?url=","isActive": true},
      {"name":"解析10","url":"https://jx.zhanlangbu.com/?url=","isActive": true}, 
      {"name":"解析11","url":"https://www.ckplayer.vip/jiexi/?url=","isActive": true},
      {"name":"解析12","url":"https://vip.blbo.cc:2222/api/?key=9f230d947680de53b544be747efa8e54&url=","isActive": true}, 
      {"name":"解析13","url":"https://b.umkan.cc/API.php?url","isActive": true}, 
      {"name":"解析15","url":"https://jx.zhanlangbu.com/?url=","isActive": true}, 
      {"name":"解析16","url":"https://h5.freejson.xyz/player/?url=","isActive": true}, 
      {"name":"解析17","url":"http://jx.fuqizhishi.com:63/API.php?appkey=feimao&url=","isActive": true}, 
      {"name":"解析18","url":"http://www.pandown.pro/app/tkys/tkysjx.php?url=","isActive": true},
      {"name":"解析19","url":"https://json.xn--9kq078cdn3a.cc/api/?key=9ksb8DzGi6xUtNf1Cm&url=","isActive": true},
      {"name":"解析20","url":"https://jx.ccabc.cc/byg/?url=","isActive": true},
      {"name":"解析21","url":"https://b.umkan.cc/API.php?url=","isActive": true},
      {"name":"解析22","url":"http://45.248.10.163:4433/json.php?wap=0&url=","isActive": true},
      {"name":"解析23","url":"http://newjiexi.gotka.top/keyu3.php?url=","isActive": true},
      {"name":"解析24","url":"http://www.miaoys.cc/vip/?url=","isActive": true},
      {"name":"解析25","url":"http://svip.key521.cn/analysis/json/?uid=22&my=acdgimotxCHLNOTX16&url=","isActive": true},
      {"name":"解析26","url":"http://47.108.39.237:55/api/jsonindex.php/?key=dp2xOsl8Nws8uFdY0E&url=","isActive": true},
      {"name":"解析27","url":"https://okjx.cc/?url=","isActive": true}
    ]
  
}
